# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from characters import models_pb2 as characters_dot_models__pb2
from characters import query_service_pb2 as characters_dot_query__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in characters/query_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EventsQueryServiceStub(object):
    """--- queries service (read models/projections)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCharacter = channel.unary_unary(
                '/questkeeper.characters.query_service.EventsQueryService/GetCharacter',
                request_serializer=characters_dot_query__service__pb2.GetCharacterRequest.SerializeToString,
                response_deserializer=characters_dot_models__pb2.Character.FromString,
                _registered_method=True)
        self.GetEventSummary = channel.unary_unary(
                '/questkeeper.characters.query_service.EventsQueryService/GetEventSummary',
                request_serializer=characters_dot_query__service__pb2.GetCharacterRequest.SerializeToString,
                response_deserializer=characters_dot_models__pb2.CharacterSummary.FromString,
                _registered_method=True)
        self.ListEvents = channel.unary_unary(
                '/questkeeper.characters.query_service.EventsQueryService/ListEvents',
                request_serializer=characters_dot_query__service__pb2.ListCharactersRequest.SerializeToString,
                response_deserializer=characters_dot_query__service__pb2.ListCharactersResponse.FromString,
                _registered_method=True)


class EventsQueryServiceServicer(object):
    """--- queries service (read models/projections)
    """

    def GetCharacter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEventSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventsQueryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCharacter': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCharacter,
                    request_deserializer=characters_dot_query__service__pb2.GetCharacterRequest.FromString,
                    response_serializer=characters_dot_models__pb2.Character.SerializeToString,
            ),
            'GetEventSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEventSummary,
                    request_deserializer=characters_dot_query__service__pb2.GetCharacterRequest.FromString,
                    response_serializer=characters_dot_models__pb2.CharacterSummary.SerializeToString,
            ),
            'ListEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEvents,
                    request_deserializer=characters_dot_query__service__pb2.ListCharactersRequest.FromString,
                    response_serializer=characters_dot_query__service__pb2.ListCharactersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'questkeeper.characters.query_service.EventsQueryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('questkeeper.characters.query_service.EventsQueryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EventsQueryService(object):
    """--- queries service (read models/projections)
    """

    @staticmethod
    def GetCharacter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.characters.query_service.EventsQueryService/GetCharacter',
            characters_dot_query__service__pb2.GetCharacterRequest.SerializeToString,
            characters_dot_models__pb2.Character.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEventSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.characters.query_service.EventsQueryService/GetEventSummary',
            characters_dot_query__service__pb2.GetCharacterRequest.SerializeToString,
            characters_dot_models__pb2.CharacterSummary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.characters.query_service.EventsQueryService/ListEvents',
            characters_dot_query__service__pb2.ListCharactersRequest.SerializeToString,
            characters_dot_query__service__pb2.ListCharactersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
