services:
  db:
    image: postgres:16-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U qk_admin -d questkeeper"]
#      interval: 5s
#      timeout: 5s
#      retries: 10
    hostname: db
    command: ["postgres", "-c", "log_connections=on", "-c", "log_hostname=on"]

  backend:
    build:
      context: .
      dockerfile: ./services/backend/Dockerfile
    env_file:
      - .env
    depends_on:
      migrations:
        condition: service_completed_successfully
    ports: ["50051:50051"]
    command: ["python", "-m", "app.main"]
    restart: unless-stopped

  migrations:
    build:
      context: .
      dockerfile: ./services/backend/Dockerfile
    env_file:
      - .env
    depends_on:
      db:
        condition: service_started
#        condition: service_healthy
    command: [ "bash", "-lc", "/app/.venv/bin/alembic -c alembic.ini upgrade head" ]
#    command: [ "bash", "-lc", "/app/.venv/bin/alembic -c alembic.ini revision --autogenerate" ]
