[project]
name = "questkeeper"
version = "0.1.0"
description = "TTRPG event management Discord bot"
requires-python = ">=3.13"
license = { text = "MIT" }
authors = [{ name = "Daria Silman daria.silman@gmail.com" }]
dependencies = [
    "alembic>=1.17.1",
    "asyncpg>=0.30.0",
    "grpcio==1.76.0",
    "grpcio-tools==1.76.0",
    "httpx>=0.28.1",
    "loguru>=0.7.3",
    "protobuf>=6.33.0",
    "psycopg>=3.2.12",
    "psycopg-binary>=3.2.12",
    "pydantic>=2.12.3",
    "pydantic-settings>=2.11.0",
    "questkeeper-api-contracts",
    "questkeeper-render-sdk",
    "redis>=7.0.1",
    "sqlalchemy[asyncio]>=2.0.44",
]

[tool.uv.workspace]
members = [
    "services/*",
    "libs/*",
]

[tool.uv.sources]
questkeeper-api-contracts = { workspace = true }
questkeeper-render-sdk = { workspace = true }
questkeeper-backend = { workspace = true }

[tool.ruff]
line-length = 100
target-version = "py313"
exclude = [
    ".venv",
    "build",
    "dist",
    "__pypackages__",
    ".uv",
    "*.pyi",
    "*/migrations/*",
    "*_pb2.py",
    "*_pb2_grpc.py",
    "*_p2p.py",
]

[tool.ruff.lint]
fixable = ["ALL"]
ignore = [
    "D100", # ignore missing docs
]
extend-select = ["I", "UP", "RUF", "TID"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.mypy]
python_version = "3.13"
strict = true
disallow_untyped_defs = true
ignore_missing_imports = true
no_implicit_optional = true
check_untyped_defs = true
warn_return_any = true

[dependency-groups]
dev = [
    "ipykernel>=7.1.0",
    "ruff>=0.14.3",
]
