"""auto-generated migration

Revision ID: b1619d07fba7
Revises:
Create Date: 2025-11-07 20:18:22.517195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1619d07fba7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.execute("CREATE SCHEMA service;")
        op.execute("CREATE SCHEMA message_queue;")
    except:
        pass

    op.create_table('characters',
    sa.Column('character_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('system', sa.Text(), nullable=False),
    sa.Column('level', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('race', sa.Text(), nullable=True),
    sa.Column('class', sa.Text(), nullable=True),
    sa.Column('subclass', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint('level >= 0', name='check_level_positive'),
    sa.PrimaryKeyConstraint('character_id'),
    schema='service'
    )
    op.create_index('ix_characters_system', 'characters', ['system'], unique=False, schema='service')
    op.create_index('ix_characters_user_id', 'characters', ['user_id'], unique=False, schema='service')
    op.create_table('events',
    sa.Column('event_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('server_id', sa.BigInteger(), nullable=False),
    sa.Column('role_mentions', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('system', sa.Text(), nullable=False),
    sa.Column('time_start', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('time_end', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'Scheduled'"), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint('time_end >= time_start', name='check_time_end_after_start'),
    sa.PrimaryKeyConstraint('event_id'),
    schema='service'
    )
    op.create_index('events_server_id_idx', 'events', ['server_id'], unique=False, schema='service')
    op.create_index('events_server_status_start_idx', 'events', ['server_id', 'status', 'time_start'], unique=False, schema='service')
    op.create_index('events_status_idx', 'events', ['status'], unique=False, schema='service')
    op.create_index('events_time_idx', 'events', ['time_start', 'time_end'], unique=False, schema='service')
    op.create_table('idempotency_keys',
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('server_id', sa.BigInteger(), nullable=False),
    sa.Column('request_hash', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('response_body_hash', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('locked_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('idempotency_key'),
    schema='service'
    )
    op.create_index('ix_idempotency_keys_server_created', 'idempotency_keys', ['server_id', 'created_at'], unique=False, schema='service')
    op.create_table('outbox',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('aggregate_type', sa.Text(), nullable=False),
    sa.Column('aggregate_id', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('available_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='message_queue'
    )
    op.create_index('ix_outbox_aggregate', 'outbox', ['aggregate_type', 'aggregate_id'], unique=False, schema='message_queue')
    op.create_index('ix_outbox_status_available', 'outbox', ['status', 'available_at'], unique=False, schema='message_queue')
    op.create_table('outbox_dlq',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('original_outbox_id', sa.UUID(), nullable=True),
    sa.Column('aggregate_type', sa.Text(), nullable=False),
    sa.Column('aggregate_id', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='message_queue'
    )
    op.create_index('ix_outbox_dlq_aggregate_created', 'outbox_dlq', ['aggregate_type', 'created_at'], unique=False, schema='message_queue')
    op.create_table('server_settings',
    sa.Column('server_id', sa.BigInteger(), nullable=False),
    sa.Column('default_announcement_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('default_system', sa.Text(), server_default=sa.text("'Pathfinder 2E'"), nullable=False),
    sa.Column('dm_notifications_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('mentionable_roles', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('server_id'),
    schema='service'
    )
    op.create_index('ix_server_settings_default_system', 'server_settings', ['default_system'], unique=False, schema='service')
    op.create_table('server_role_mapping',
    sa.Column('server_id', sa.BigInteger(), nullable=False),
    sa.Column('discord_role_id', sa.BigInteger(), nullable=False),
    sa.Column('app_role', sa.Text(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['service.server_settings.server_id'], ),
    sa.PrimaryKeyConstraint('server_id', 'discord_role_id'),
    schema='service'
    )
    op.create_index('ix_server_role_mapping_server_id', 'server_role_mapping', ['server_id'], unique=False, schema='service')
    op.create_table('sessions',
    sa.Column('session_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('server_id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('gm_user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_mentions', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('system', sa.Text(), nullable=False),
    sa.Column('vtt_link', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('additional_links', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'Scheduled'"), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint('capacity >= 0', name='check_capacity_positive'),
    sa.CheckConstraint('duration_minutes >= 0', name='check_duration_positive'),
    sa.ForeignKeyConstraint(['event_id'], ['service.events.event_id'], ),
    sa.PrimaryKeyConstraint('session_id'),
    schema='service'
    )
    op.create_index('ix_sessions_event_id', 'sessions', ['event_id'], unique=False, schema='service')
    op.create_index('ix_sessions_gm_user_id', 'sessions', ['gm_user_id'], unique=False, schema='service')
    op.create_index('ix_sessions_server_id', 'sessions', ['server_id'], unique=False, schema='service')
    op.create_index('ix_sessions_server_status_time', 'sessions', ['server_id', 'status', 'time'], unique=False, schema='service')
    op.create_index('ix_sessions_status', 'sessions', ['status'], unique=False, schema='service')
    op.create_index('ix_sessions_time', 'sessions', ['time'], unique=False, schema='service')
    op.create_table('character_history',
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['service.characters.character_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['service.sessions.session_id'], ),
    sa.PrimaryKeyConstraint('character_id', 'session_id'),
    schema='service'
    )
    op.create_index('ix_character_history_character_created', 'character_history', ['character_id', 'created_at'], unique=False, schema='service')
    op.create_index('ix_character_history_session_id', 'character_history', ['session_id'], unique=False, schema='service')
    op.create_table('signups',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['service.characters.character_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['service.sessions.session_id'], ),
    sa.PrimaryKeyConstraint('session_id', 'user_id'),
    schema='service'
    )
    op.create_index('ix_signups_character_id', 'signups', ['character_id'], unique=False, schema='service')
    op.create_index('ix_signups_session_role', 'signups', ['session_id', 'role'], unique=False, schema='service')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_signups_session_role', table_name='signups', schema='service')
    op.drop_index('ix_signups_character_id', table_name='signups', schema='service')
    op.drop_table('signups', schema='service')
    op.drop_index('ix_character_history_session_id', table_name='character_history', schema='service')
    op.drop_index('ix_character_history_character_created', table_name='character_history', schema='service')
    op.drop_table('character_history', schema='service')
    op.drop_index('ix_sessions_time', table_name='sessions', schema='service')
    op.drop_index('ix_sessions_status', table_name='sessions', schema='service')
    op.drop_index('ix_sessions_server_status_time', table_name='sessions', schema='service')
    op.drop_index('ix_sessions_server_id', table_name='sessions', schema='service')
    op.drop_index('ix_sessions_gm_user_id', table_name='sessions', schema='service')
    op.drop_index('ix_sessions_event_id', table_name='sessions', schema='service')
    op.drop_table('sessions', schema='service')
    op.drop_index('ix_server_role_mapping_server_id', table_name='server_role_mapping', schema='service')
    op.drop_table('server_role_mapping', schema='service')
    op.drop_index('ix_server_settings_default_system', table_name='server_settings', schema='service')
    op.drop_table('server_settings', schema='service')
    op.drop_index('ix_outbox_dlq_aggregate_created', table_name='outbox_dlq', schema='message_queue')
    op.drop_table('outbox_dlq', schema='message_queue')
    op.drop_index('ix_outbox_status_available', table_name='outbox', schema='message_queue')
    op.drop_index('ix_outbox_aggregate', table_name='outbox', schema='message_queue')
    op.drop_table('outbox', schema='message_queue')
    op.drop_index('ix_idempotency_keys_server_created', table_name='idempotency_keys', schema='service')
    op.drop_table('idempotency_keys', schema='service')
    op.drop_index('events_time_idx', table_name='events', schema='service')
    op.drop_index('events_status_idx', table_name='events', schema='service')
    op.drop_index('events_server_status_start_idx', table_name='events', schema='service')
    op.drop_index('events_server_id_idx', table_name='events', schema='service')
    op.drop_table('events', schema='service')
    op.drop_index('ix_characters_user_id', table_name='characters', schema='service')
    op.drop_index('ix_characters_system', table_name='characters', schema='service')
    op.drop_table('characters', schema='service')
