# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: events/commands_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'events/commands_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from events import models_pb2 as events_dot_models__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x65vents/commands_service.proto\x12#questkeeper.events.commands_service\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13\x65vents/models.proto\"o\n\x11\x45\x64itBasicsRequest\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07summary\x18\x03 \x01(\t\x12\x0e\n\x06system\x18\x04 \x01(\t\x12\x18\n\x10\x65xpected_version\x18\x05 \x01(\x04\"\xa1\x01\n\x13\x45\x64itScheduleRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12.\n\ntime_start\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x08time_end\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x18\n\x10\x65xpected_version\x18\x05 \x01(\x04\"_\n\x17\x45\x64itOrganizationRequest\x12\x10\n\x08location\x18\x01 \x01(\t\x12\x18\n\x10\x61\x64\x64itional_links\x18\x02 \x03(\t\x12\x18\n\x10\x65xpected_version\x18\x03 \x01(\x04\"A\n\x13PublishEventRequest\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x18\n\x10\x65xpected_version\x18\x02 \x01(\x04\"@\n\x12\x43\x61ncelEventRequest\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x18\n\x10\x65xpected_version\x18\x02 \x01(\x04\x32\x8b\x05\n\x14\x45ventsCommandService\x12U\n\x0b\x43reateEvent\x12$.questkeeper.events.models.EventInfo\x1a .questkeeper.events.models.Event\x12\x66\n\nEditBasics\x12\x36.questkeeper.events.commands_service.EditBasicsRequest\x1a .questkeeper.events.models.Event\x12j\n\x0c\x45\x64itSchedule\x12\x38.questkeeper.events.commands_service.EditScheduleRequest\x1a .questkeeper.events.models.Event\x12r\n\x10\x45\x64itOrganization\x12<.questkeeper.events.commands_service.EditOrganizationRequest\x1a .questkeeper.events.models.Event\x12j\n\x0cPublishEvent\x12\x38.questkeeper.events.commands_service.PublishEventRequest\x1a .questkeeper.events.models.Event\x12h\n\x0b\x43\x61ncelEvent\x12\x37.questkeeper.events.commands_service.CancelEventRequest\x1a .questkeeper.events.models.Eventb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'events.commands_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EDITBASICSREQUEST']._serialized_start=124
  _globals['_EDITBASICSREQUEST']._serialized_end=235
  _globals['_EDITSCHEDULEREQUEST']._serialized_start=238
  _globals['_EDITSCHEDULEREQUEST']._serialized_end=399
  _globals['_EDITORGANIZATIONREQUEST']._serialized_start=401
  _globals['_EDITORGANIZATIONREQUEST']._serialized_end=496
  _globals['_PUBLISHEVENTREQUEST']._serialized_start=498
  _globals['_PUBLISHEVENTREQUEST']._serialized_end=563
  _globals['_CANCELEVENTREQUEST']._serialized_start=565
  _globals['_CANCELEVENTREQUEST']._serialized_end=629
  _globals['_EVENTSCOMMANDSERVICE']._serialized_start=632
  _globals['_EVENTSCOMMANDSERVICE']._serialized_end=1283
# @@protoc_insertion_point(module_scope)
