# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: events/query_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'events/query_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
import common_pb2 as common__pb2
from events import models_pb2 as events_dot_models__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x65vents/query_service.proto\x12 questkeeper.events.query_service\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0c\x63ommon.proto\x1a\x13\x65vents/models.proto\"#\n\x0fGetEventRequest\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\"\xc9\x01\n\x11ListEventsRequest\x12\x11\n\tserver_id\x18\x01 \x01(\t\x12\x0e\n\x06system\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12)\n\x05start\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\'\n\x03\x65nd\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12-\n\x04page\x18\x06 \x01(\x0b\x32\x1f.questkeeper.common.PageRequest\"t\n\x12ListEventsResponse\x12\x36\n\x05items\x18\x01 \x03(\x0b\x32\'.questkeeper.events.models.EventSummary\x12&\n\x04page\x18\x02 \x01(\x0b\x32\x18.questkeeper.common.Page2\xc6\x03\n\x12\x45ventsQueryService\x12_\n\x08GetEvent\x12\x31.questkeeper.events.query_service.GetEventRequest\x1a .questkeeper.events.models.Event\x12g\n\x0cGetEventView\x12\x31.questkeeper.events.query_service.GetEventRequest\x1a$.questkeeper.events.models.EventView\x12m\n\x0fGetEventSummary\x12\x31.questkeeper.events.query_service.GetEventRequest\x1a\'.questkeeper.events.models.EventSummary\x12w\n\nListEvents\x12\x33.questkeeper.events.query_service.ListEventsRequest\x1a\x34.questkeeper.events.query_service.ListEventsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'events.query_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETEVENTREQUEST']._serialized_start=132
  _globals['_GETEVENTREQUEST']._serialized_end=167
  _globals['_LISTEVENTSREQUEST']._serialized_start=170
  _globals['_LISTEVENTSREQUEST']._serialized_end=371
  _globals['_LISTEVENTSRESPONSE']._serialized_start=373
  _globals['_LISTEVENTSRESPONSE']._serialized_end=489
  _globals['_EVENTSQUERYSERVICE']._serialized_start=492
  _globals['_EVENTSQUERYSERVICE']._serialized_end=946
# @@protoc_insertion_point(module_scope)
