[build-system]
requires = ["hatchling>=1.25"]
build-backend = "hatchling.build"

[project]
name = "questkeeper-backend"
version = "0.1.0"
description = "Backend domain service"
requires-python = ">=3.13"
dependencies = []


[tool.hatch.build.targets.wheel]
packages = ["client/src/qk_backend_client"]
