syntax = "proto3";

package questkeeper.events;

import "google/protobuf/timestamp.proto";
import "qk_api_contracts/grpc/events/models.proto";

// --- domain commands service (write) ---
service EventsCommands {
  // event lifecycle
  rpc CreateEvent(models.EventInfo) returns (models.Event);
  rpc EditBasics(EditBasicsRequest) returns (models.Event);
  rpc EditSchedule(EditScheduleRequest) returns (models.Event);
  rpc EditOrganization(EditOrganizationRequest) returns (models.Event);
  rpc PublishEvent(PublishEventRequest) returns (models.Event);
  rpc CancelEvent(CancelEventRequest) returns (models.Event);
}

// --- event commands ---

// edit

message EditBasicsRequest {
  string event_id = 1;
  string title = 2;
  string summary = 3;
  string system = 4;

  uint64 expected_version = 5;
}

message EditScheduleRequest {
  string session_id = 1;
  google.protobuf.Timestamp time_start = 2;
  google.protobuf.Timestamp time_end = 3;

  uint64 expected_version = 5;
}

message EditOrganizationRequest {
  string location = 1;
  repeated string additional_links = 2;

  uint64 expected_version = 3;
}


// publish session

message PublishEventRequest {
  string event_id = 1;

  uint64 expected_version = 2;
}

// cancel session

message CancelEventRequest {
  string event_id = 1;

  uint64 expected_version = 2;
}
