syntax = "proto3";

package questkeeper.events;

import "google/protobuf/timestamp.proto";
import "qk_api_contracts/grpc/common.proto";
import "qk_api_contracts/grpc/events/models.proto";

// --- queries service (read models/projections)
service EventsQuery {
  rpc GetEvent(GetEventRequest) returns (models.Event);
  rpc GetEventView(GetEventRequest) returns (models.EventView);
  rpc GetEventSummary(GetEventRequest) returns (models.EventSummary);
  rpc ListEvents(ListEventsRequest) returns (ListEventsResponse);
}

// --- requests ---

message GetEventRequest {
  string event_id = 1;
}

message ListEventsRequest {
  string server_id = 1;
  string system = 2;
  string status = 3;
  google.protobuf.Timestamp start = 4;
  google.protobuf.Timestamp end = 5;

  common.PageRequest page = 6;
}

message ListEventsResponse {
  repeated models.EventSummary items = 1;
  common.Page page = 2;
}