syntax = "proto3";

package questkeeper.v1.events;

import "google/protobuf/timestamp.proto";
import "qk_api_contracts/grpc/common.proto";
import "qk_api_contracts/grpc/events/models.proto";

service Events {
  // commands
  rpc CreateEvent(models.EventInfo) returns (models.Event);
  rpc EditBasics(EditBasicsRequest) returns (models.Event);
  rpc EditSchedule(EditScheduleRequest) returns (models.Event);
  rpc EditOrganization(EditOrganizationRequest) returns (models.Event);
  rpc PublishEvent(EventOperationRequest) returns (models.Event);
  rpc CancelEvent(EventOperationRequest) returns (models.Event);

  // queries
  rpc GetEvent(GetEventRequest) returns (models.Event);
  rpc GetEventView(GetEventRequest) returns (models.EventView);
  rpc GetEventSummary(GetEventRequest) returns (models.EventSummary);
  rpc ListEvents(ListEventsRequest) returns (ListEventsResponse);
}

// --- commands ---

// edit

message EditBasicsRequest {
  string event_id = 1;
  string title = 2;
  string summary = 3;
  string system = 4;

  uint64 expected_version = 5;
}

message EditScheduleRequest {
  string session_id = 1;
  google.protobuf.Timestamp time_start = 2;
  google.protobuf.Timestamp time_end = 3;

  uint64 expected_version = 5;
}

message EditOrganizationRequest {
  string location = 1;
  repeated string additional_links = 2;

  uint64 expected_version = 3;
}

message EventOperationRequest {
  string event_id = 1;

  uint64 expected_version = 2;
}


// --- queries ---

message GetEventRequest {
  string event_id = 1;
}

message ListEventsRequest {
  string server_id = 1;
  string system = 2;
  string status = 3;
  google.protobuf.Timestamp start = 4;
  google.protobuf.Timestamp end = 5;

  common.PageRequest page = 6;
}

message ListEventsResponse {
  repeated models.EventSummary items = 1;
  common.Page page = 2;
}