# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: qk_api_contracts/grpc/characters/query_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'qk_api_contracts/grpc/characters/query_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from qk_api_contracts.grpc import common_pb2 as qk__api__contracts_dot_grpc_dot_common__pb2
from qk_api_contracts.grpc.characters import models_pb2 as qk__api__contracts_dot_grpc_dot_characters_dot_models__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4qk_api_contracts/grpc/characters/query_service.proto\x12\x16questkeeper.characters\x1a\"qk_api_contracts/grpc/common.proto\x1a-qk_api_contracts/grpc/characters/models.proto\"*\n\x12\x43haracterIdRequest\x12\x14\n\x0c\x63haracter_id\x18\x01 \x01(\t\"g\n\x15ListCharactersRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\x0e\n\x06system\x18\x02 \x01(\t\x12-\n\x04page\x18\x06 \x01(\x0b\x32\x1f.questkeeper.common.PageRequest\"y\n\x16ListCharactersResponse\x12\x37\n\x05items\x18\x01 \x03(\x0b\x32(.questkeeper.characters.models.Character\x12&\n\x04page\x18\x02 \x01(\x0b\x32\x18.questkeeper.common.Page\"\x8f\x01\n\x13PlayHistoryResponse\x12:\n\x07records\x18\x01 \x03(\x0b\x32).questkeeper.characters.models.PlayRecord\x12\x14\n\x0c\x63haracter_id\x18\x02 \x01(\t\x12&\n\x04page\x18\x03 \x01(\x0b\x32\x18.questkeeper.common.Page2\xdc\x02\n\x0f\x43haractersQuery\x12\x64\n\x0cGetCharacter\x12*.questkeeper.characters.CharacterIdRequest\x1a(.questkeeper.characters.models.Character\x12o\n\x0eListCharacters\x12-.questkeeper.characters.ListCharactersRequest\x1a..questkeeper.characters.ListCharactersResponse\x12r\n\x17GetCharacterPlayHistory\x12*.questkeeper.characters.CharacterIdRequest\x1a+.questkeeper.characters.PlayHistoryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'qk_api_contracts.grpc.characters.query_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHARACTERIDREQUEST']._serialized_start=163
  _globals['_CHARACTERIDREQUEST']._serialized_end=205
  _globals['_LISTCHARACTERSREQUEST']._serialized_start=207
  _globals['_LISTCHARACTERSREQUEST']._serialized_end=310
  _globals['_LISTCHARACTERSRESPONSE']._serialized_start=312
  _globals['_LISTCHARACTERSRESPONSE']._serialized_end=433
  _globals['_PLAYHISTORYRESPONSE']._serialized_start=436
  _globals['_PLAYHISTORYRESPONSE']._serialized_end=579
  _globals['_CHARACTERSQUERY']._serialized_start=582
  _globals['_CHARACTERSQUERY']._serialized_end=930
# @@protoc_insertion_point(module_scope)
