# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: characters/query_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'characters/query_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2
from characters import models_pb2 as characters_dot_models__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x63haracters/query_service.proto\x12$questkeeper.characters.query_service\x1a\x0c\x63ommon.proto\x1a\x17\x63haracters/models.proto\"\'\n\x13GetCharacterRequest\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\"g\n\x15ListCharactersRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\x0e\n\x06system\x18\x02 \x01(\t\x12-\n\x04page\x18\x06 \x01(\x0b\x32\x1f.questkeeper.common.PageRequest\"\x80\x01\n\x16ListCharactersResponse\x12>\n\x05items\x18\x01 \x03(\x0b\x32/.questkeeper.characters.models.CharacterSummary\x12&\n\x04page\x18\x02 \x01(\x0b\x32\x18.questkeeper.common.Page2\x98\x03\n\x0f\x43haractersQuery\x12s\n\x0cGetCharacter\x12\x39.questkeeper.characters.query_service.GetCharacterRequest\x1a(.questkeeper.characters.models.Character\x12\x81\x01\n\x13GetCharacterSummary\x12\x39.questkeeper.characters.query_service.GetCharacterRequest\x1a/.questkeeper.characters.models.CharacterSummary\x12\x8b\x01\n\x0eListCharacters\x12;.questkeeper.characters.query_service.ListCharactersRequest\x1a<.questkeeper.characters.query_service.ListCharactersResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'characters.query_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETCHARACTERREQUEST']._serialized_start=111
  _globals['_GETCHARACTERREQUEST']._serialized_end=150
  _globals['_LISTCHARACTERSREQUEST']._serialized_start=152
  _globals['_LISTCHARACTERSREQUEST']._serialized_end=255
  _globals['_LISTCHARACTERSRESPONSE']._serialized_start=258
  _globals['_LISTCHARACTERSRESPONSE']._serialized_end=386
  _globals['_CHARACTERSQUERY']._serialized_start=389
  _globals['_CHARACTERSQUERY']._serialized_end=797
# @@protoc_insertion_point(module_scope)
