# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from qk_api_contracts.grpc.sessions import commands_service_pb2 as qk__api__contracts_dot_grpc_dot_sessions_dot_commands__service__pb2
from qk_api_contracts.grpc.sessions import models_pb2 as qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in qk_api_contracts/grpc/sessions/commands_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SessionCommandsStub(object):
    """--- domain commands service (write) ---
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSession = channel.unary_unary(
                '/questkeeper.sessions.SessionCommands/CreateSession',
                request_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.SessionInfo.SerializeToString,
                response_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Session.FromString,
                _registered_method=True)
        self.EditBasics = channel.unary_unary(
                '/questkeeper.sessions.SessionCommands/EditBasics',
                request_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_commands__service__pb2.EditBasicsRequest.SerializeToString,
                response_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Session.FromString,
                _registered_method=True)
        self.EditSchedule = channel.unary_unary(
                '/questkeeper.sessions.SessionCommands/EditSchedule',
                request_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_commands__service__pb2.EditScheduleRequest.SerializeToString,
                response_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Session.FromString,
                _registered_method=True)
        self.EditCapacity = channel.unary_unary(
                '/questkeeper.sessions.SessionCommands/EditCapacity',
                request_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_commands__service__pb2.EditCapacityRequest.SerializeToString,
                response_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Session.FromString,
                _registered_method=True)
        self.EditOrganization = channel.unary_unary(
                '/questkeeper.sessions.SessionCommands/EditOrganization',
                request_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_commands__service__pb2.EditOrganizationRequest.SerializeToString,
                response_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Session.FromString,
                _registered_method=True)
        self.EditGM = channel.unary_unary(
                '/questkeeper.sessions.SessionCommands/EditGM',
                request_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_commands__service__pb2.EditGMRequest.SerializeToString,
                response_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Session.FromString,
                _registered_method=True)
        self.PublishSession = channel.unary_unary(
                '/questkeeper.sessions.SessionCommands/PublishSession',
                request_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_commands__service__pb2.PublishSessionRequest.SerializeToString,
                response_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Session.FromString,
                _registered_method=True)
        self.CancelSession = channel.unary_unary(
                '/questkeeper.sessions.SessionCommands/CancelSession',
                request_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_commands__service__pb2.CancelSessionRequest.SerializeToString,
                response_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Session.FromString,
                _registered_method=True)


class SessionCommandsServicer(object):
    """--- domain commands service (write) ---
    """

    def CreateSession(self, request, context):
        """session lifecycle
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditBasics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditCapacity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditOrganization(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditGM(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SessionCommandsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.SessionInfo.FromString,
                    response_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Session.SerializeToString,
            ),
            'EditBasics': grpc.unary_unary_rpc_method_handler(
                    servicer.EditBasics,
                    request_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_commands__service__pb2.EditBasicsRequest.FromString,
                    response_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Session.SerializeToString,
            ),
            'EditSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.EditSchedule,
                    request_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_commands__service__pb2.EditScheduleRequest.FromString,
                    response_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Session.SerializeToString,
            ),
            'EditCapacity': grpc.unary_unary_rpc_method_handler(
                    servicer.EditCapacity,
                    request_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_commands__service__pb2.EditCapacityRequest.FromString,
                    response_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Session.SerializeToString,
            ),
            'EditOrganization': grpc.unary_unary_rpc_method_handler(
                    servicer.EditOrganization,
                    request_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_commands__service__pb2.EditOrganizationRequest.FromString,
                    response_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Session.SerializeToString,
            ),
            'EditGM': grpc.unary_unary_rpc_method_handler(
                    servicer.EditGM,
                    request_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_commands__service__pb2.EditGMRequest.FromString,
                    response_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Session.SerializeToString,
            ),
            'PublishSession': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishSession,
                    request_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_commands__service__pb2.PublishSessionRequest.FromString,
                    response_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Session.SerializeToString,
            ),
            'CancelSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelSession,
                    request_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_commands__service__pb2.CancelSessionRequest.FromString,
                    response_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Session.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'questkeeper.sessions.SessionCommands', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('questkeeper.sessions.SessionCommands', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SessionCommands(object):
    """--- domain commands service (write) ---
    """

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.sessions.SessionCommands/CreateSession',
            qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.SessionInfo.SerializeToString,
            qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EditBasics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.sessions.SessionCommands/EditBasics',
            qk__api__contracts_dot_grpc_dot_sessions_dot_commands__service__pb2.EditBasicsRequest.SerializeToString,
            qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EditSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.sessions.SessionCommands/EditSchedule',
            qk__api__contracts_dot_grpc_dot_sessions_dot_commands__service__pb2.EditScheduleRequest.SerializeToString,
            qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EditCapacity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.sessions.SessionCommands/EditCapacity',
            qk__api__contracts_dot_grpc_dot_sessions_dot_commands__service__pb2.EditCapacityRequest.SerializeToString,
            qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EditOrganization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.sessions.SessionCommands/EditOrganization',
            qk__api__contracts_dot_grpc_dot_sessions_dot_commands__service__pb2.EditOrganizationRequest.SerializeToString,
            qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EditGM(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.sessions.SessionCommands/EditGM',
            qk__api__contracts_dot_grpc_dot_sessions_dot_commands__service__pb2.EditGMRequest.SerializeToString,
            qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.sessions.SessionCommands/PublishSession',
            qk__api__contracts_dot_grpc_dot_sessions_dot_commands__service__pb2.PublishSessionRequest.SerializeToString,
            qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.sessions.SessionCommands/CancelSession',
            qk__api__contracts_dot_grpc_dot_sessions_dot_commands__service__pb2.CancelSessionRequest.SerializeToString,
            qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SignupCommandsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SignupToSession = channel.unary_unary(
                '/questkeeper.sessions.SignupCommands/SignupToSession',
                request_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.SignupInfo.SerializeToString,
                response_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Signup.FromString,
                _registered_method=True)
        self.SwitchReserve = channel.unary_unary(
                '/questkeeper.sessions.SignupCommands/SwitchReserve',
                request_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_commands__service__pb2.SwitchReserveRequest.SerializeToString,
                response_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Signup.FromString,
                _registered_method=True)
        self.SwitchMain = channel.unary_unary(
                '/questkeeper.sessions.SignupCommands/SwitchMain',
                request_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_commands__service__pb2.SwitchMainRequest.SerializeToString,
                response_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Signup.FromString,
                _registered_method=True)
        self.LeaveSession = channel.unary_unary(
                '/questkeeper.sessions.SignupCommands/LeaveSession',
                request_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_commands__service__pb2.SignOutRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.SetCharacter = channel.unary_unary(
                '/questkeeper.sessions.SignupCommands/SetCharacter',
                request_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_commands__service__pb2.SetCharacterRequest.SerializeToString,
                response_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Signup.FromString,
                _registered_method=True)


class SignupCommandsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SignupToSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SwitchReserve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SwitchMain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LeaveSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetCharacter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SignupCommandsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SignupToSession': grpc.unary_unary_rpc_method_handler(
                    servicer.SignupToSession,
                    request_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.SignupInfo.FromString,
                    response_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Signup.SerializeToString,
            ),
            'SwitchReserve': grpc.unary_unary_rpc_method_handler(
                    servicer.SwitchReserve,
                    request_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_commands__service__pb2.SwitchReserveRequest.FromString,
                    response_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Signup.SerializeToString,
            ),
            'SwitchMain': grpc.unary_unary_rpc_method_handler(
                    servicer.SwitchMain,
                    request_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_commands__service__pb2.SwitchMainRequest.FromString,
                    response_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Signup.SerializeToString,
            ),
            'LeaveSession': grpc.unary_unary_rpc_method_handler(
                    servicer.LeaveSession,
                    request_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_commands__service__pb2.SignOutRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SetCharacter': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCharacter,
                    request_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_commands__service__pb2.SetCharacterRequest.FromString,
                    response_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Signup.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'questkeeper.sessions.SignupCommands', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('questkeeper.sessions.SignupCommands', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SignupCommands(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SignupToSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.sessions.SignupCommands/SignupToSession',
            qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.SignupInfo.SerializeToString,
            qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Signup.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SwitchReserve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.sessions.SignupCommands/SwitchReserve',
            qk__api__contracts_dot_grpc_dot_sessions_dot_commands__service__pb2.SwitchReserveRequest.SerializeToString,
            qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Signup.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SwitchMain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.sessions.SignupCommands/SwitchMain',
            qk__api__contracts_dot_grpc_dot_sessions_dot_commands__service__pb2.SwitchMainRequest.SerializeToString,
            qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Signup.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LeaveSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.sessions.SignupCommands/LeaveSession',
            qk__api__contracts_dot_grpc_dot_sessions_dot_commands__service__pb2.SignOutRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetCharacter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.sessions.SignupCommands/SetCharacter',
            qk__api__contracts_dot_grpc_dot_sessions_dot_commands__service__pb2.SetCharacterRequest.SerializeToString,
            qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Signup.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
