# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: qk_api_contracts/grpc/sessions/query_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'qk_api_contracts/grpc/sessions/query_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from qk_api_contracts.grpc import common_pb2 as qk__api__contracts_dot_grpc_dot_common__pb2
from qk_api_contracts.grpc.sessions import models_pb2 as qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2qk_api_contracts/grpc/sessions/query_service.proto\x12\x14questkeeper.sessions\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\"qk_api_contracts/grpc/common.proto\x1a+qk_api_contracts/grpc/sessions/models.proto\"\'\n\x11GetSessionRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\"\x82\x02\n\x13ListSessionsRequest\x12\x11\n\tserver_id\x18\x01 \x01(\t\x12\x12\n\ngm_user_id\x18\x02 \x01(\x03\x12\x0f\n\x07user_id\x18\x03 \x01(\x03\x12\x0e\n\x06system\x18\x04 \x01(\t\x12\x10\n\x08\x65vent_id\x18\x05 \x01(\t\x12\x0e\n\x06status\x18\x06 \x01(\t\x12)\n\x05start\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\'\n\x03\x65nd\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12-\n\x04page\x18\t \x01(\x0b\x32\x1f.questkeeper.common.PageRequest\"z\n\x14ListSessionsResponse\x12:\n\x05items\x18\x01 \x03(\x0b\x32+.questkeeper.sessions.models.SessionSummary\x12&\n\x04page\x18\x02 \x01(\x0b\x32\x18.questkeeper.common.Page2\xa3\x03\n\rSessionsQuery\x12[\n\nGetSession\x12\'.questkeeper.sessions.GetSessionRequest\x1a$.questkeeper.sessions.models.Session\x12\x63\n\x0eGetSessionView\x12\'.questkeeper.sessions.GetSessionRequest\x1a(.questkeeper.sessions.models.SessionView\x12i\n\x11GetSessionSummary\x12\'.questkeeper.sessions.GetSessionRequest\x1a+.questkeeper.sessions.models.SessionSummary\x12\x65\n\x0cListSessions\x12).questkeeper.sessions.ListSessionsRequest\x1a*.questkeeper.sessions.ListSessionsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'qk_api_contracts.grpc.sessions.query_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETSESSIONREQUEST']._serialized_start=190
  _globals['_GETSESSIONREQUEST']._serialized_end=229
  _globals['_LISTSESSIONSREQUEST']._serialized_start=232
  _globals['_LISTSESSIONSREQUEST']._serialized_end=490
  _globals['_LISTSESSIONSRESPONSE']._serialized_start=492
  _globals['_LISTSESSIONSRESPONSE']._serialized_end=614
  _globals['_SESSIONSQUERY']._serialized_start=617
  _globals['_SESSIONSQUERY']._serialized_end=1036
# @@protoc_insertion_point(module_scope)
