# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from qk_api_contracts.grpc.sessions import models_pb2 as qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2
from qk_api_contracts.grpc.sessions import query_service_pb2 as qk__api__contracts_dot_grpc_dot_sessions_dot_query__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in qk_api_contracts/grpc/sessions/query_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SessionsQueryStub(object):
    """--- queries service (read models/projections)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSession = channel.unary_unary(
                '/questkeeper.sessions.SessionsQuery/GetSession',
                request_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_query__service__pb2.GetSessionRequest.SerializeToString,
                response_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Session.FromString,
                _registered_method=True)
        self.GetSessionView = channel.unary_unary(
                '/questkeeper.sessions.SessionsQuery/GetSessionView',
                request_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_query__service__pb2.GetSessionRequest.SerializeToString,
                response_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.SessionView.FromString,
                _registered_method=True)
        self.GetSessionSummary = channel.unary_unary(
                '/questkeeper.sessions.SessionsQuery/GetSessionSummary',
                request_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_query__service__pb2.GetSessionRequest.SerializeToString,
                response_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.SessionSummary.FromString,
                _registered_method=True)
        self.ListSessions = channel.unary_unary(
                '/questkeeper.sessions.SessionsQuery/ListSessions',
                request_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_query__service__pb2.ListSessionsRequest.SerializeToString,
                response_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_query__service__pb2.ListSessionsResponse.FromString,
                _registered_method=True)


class SessionsQueryServicer(object):
    """--- queries service (read models/projections)
    """

    def GetSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSessionView(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSessionSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSessions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SessionsQueryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSession': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSession,
                    request_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_query__service__pb2.GetSessionRequest.FromString,
                    response_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Session.SerializeToString,
            ),
            'GetSessionView': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSessionView,
                    request_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_query__service__pb2.GetSessionRequest.FromString,
                    response_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.SessionView.SerializeToString,
            ),
            'GetSessionSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSessionSummary,
                    request_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_query__service__pb2.GetSessionRequest.FromString,
                    response_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.SessionSummary.SerializeToString,
            ),
            'ListSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessions,
                    request_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_query__service__pb2.ListSessionsRequest.FromString,
                    response_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_query__service__pb2.ListSessionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'questkeeper.sessions.SessionsQuery', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('questkeeper.sessions.SessionsQuery', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SessionsQuery(object):
    """--- queries service (read models/projections)
    """

    @staticmethod
    def GetSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.sessions.SessionsQuery/GetSession',
            qk__api__contracts_dot_grpc_dot_sessions_dot_query__service__pb2.GetSessionRequest.SerializeToString,
            qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSessionView(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.sessions.SessionsQuery/GetSessionView',
            qk__api__contracts_dot_grpc_dot_sessions_dot_query__service__pb2.GetSessionRequest.SerializeToString,
            qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.SessionView.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSessionSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.sessions.SessionsQuery/GetSessionSummary',
            qk__api__contracts_dot_grpc_dot_sessions_dot_query__service__pb2.GetSessionRequest.SerializeToString,
            qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.SessionSummary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.sessions.SessionsQuery/ListSessions',
            qk__api__contracts_dot_grpc_dot_sessions_dot_query__service__pb2.ListSessionsRequest.SerializeToString,
            qk__api__contracts_dot_grpc_dot_sessions_dot_query__service__pb2.ListSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
