# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from qk_api_contracts.grpc.sessions import models_pb2 as qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2
from qk_api_contracts.grpc.sessions import service_pb2 as qk__api__contracts_dot_grpc_dot_sessions_dot_service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in qk_api_contracts/grpc/sessions/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SessionsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSession = channel.unary_unary(
                '/questkeeper.v1.sessions.Sessions/CreateSession',
                request_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.SessionInfo.SerializeToString,
                response_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Session.FromString,
                _registered_method=True)
        self.EditBasics = channel.unary_unary(
                '/questkeeper.v1.sessions.Sessions/EditBasics',
                request_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_service__pb2.EditBasicsRequest.SerializeToString,
                response_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Session.FromString,
                _registered_method=True)
        self.EditSchedule = channel.unary_unary(
                '/questkeeper.v1.sessions.Sessions/EditSchedule',
                request_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_service__pb2.EditScheduleRequest.SerializeToString,
                response_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Session.FromString,
                _registered_method=True)
        self.EditCapacity = channel.unary_unary(
                '/questkeeper.v1.sessions.Sessions/EditCapacity',
                request_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_service__pb2.EditCapacityRequest.SerializeToString,
                response_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Session.FromString,
                _registered_method=True)
        self.EditOrganization = channel.unary_unary(
                '/questkeeper.v1.sessions.Sessions/EditOrganization',
                request_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_service__pb2.EditOrganizationRequest.SerializeToString,
                response_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Session.FromString,
                _registered_method=True)
        self.EditGM = channel.unary_unary(
                '/questkeeper.v1.sessions.Sessions/EditGM',
                request_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_service__pb2.EditGMRequest.SerializeToString,
                response_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Session.FromString,
                _registered_method=True)
        self.PublishSession = channel.unary_unary(
                '/questkeeper.v1.sessions.Sessions/PublishSession',
                request_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_service__pb2.SessionOperationRequest.SerializeToString,
                response_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Session.FromString,
                _registered_method=True)
        self.CancelSession = channel.unary_unary(
                '/questkeeper.v1.sessions.Sessions/CancelSession',
                request_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_service__pb2.SessionOperationRequest.SerializeToString,
                response_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Session.FromString,
                _registered_method=True)
        self.GetSession = channel.unary_unary(
                '/questkeeper.v1.sessions.Sessions/GetSession',
                request_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_service__pb2.GetSessionRequest.SerializeToString,
                response_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Session.FromString,
                _registered_method=True)
        self.GetSessionView = channel.unary_unary(
                '/questkeeper.v1.sessions.Sessions/GetSessionView',
                request_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_service__pb2.GetSessionRequest.SerializeToString,
                response_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.SessionView.FromString,
                _registered_method=True)
        self.GetSessionSummary = channel.unary_unary(
                '/questkeeper.v1.sessions.Sessions/GetSessionSummary',
                request_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_service__pb2.GetSessionRequest.SerializeToString,
                response_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.SessionSummary.FromString,
                _registered_method=True)
        self.ListSessions = channel.unary_unary(
                '/questkeeper.v1.sessions.Sessions/ListSessions',
                request_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_service__pb2.ListSessionsRequest.SerializeToString,
                response_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_service__pb2.ListSessionsResponse.FromString,
                _registered_method=True)


class SessionsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateSession(self, request, context):
        """commands
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditBasics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditCapacity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditOrganization(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditGM(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSession(self, request, context):
        """queries
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSessionView(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSessionSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSessions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SessionsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.SessionInfo.FromString,
                    response_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Session.SerializeToString,
            ),
            'EditBasics': grpc.unary_unary_rpc_method_handler(
                    servicer.EditBasics,
                    request_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_service__pb2.EditBasicsRequest.FromString,
                    response_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Session.SerializeToString,
            ),
            'EditSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.EditSchedule,
                    request_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_service__pb2.EditScheduleRequest.FromString,
                    response_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Session.SerializeToString,
            ),
            'EditCapacity': grpc.unary_unary_rpc_method_handler(
                    servicer.EditCapacity,
                    request_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_service__pb2.EditCapacityRequest.FromString,
                    response_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Session.SerializeToString,
            ),
            'EditOrganization': grpc.unary_unary_rpc_method_handler(
                    servicer.EditOrganization,
                    request_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_service__pb2.EditOrganizationRequest.FromString,
                    response_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Session.SerializeToString,
            ),
            'EditGM': grpc.unary_unary_rpc_method_handler(
                    servicer.EditGM,
                    request_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_service__pb2.EditGMRequest.FromString,
                    response_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Session.SerializeToString,
            ),
            'PublishSession': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishSession,
                    request_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_service__pb2.SessionOperationRequest.FromString,
                    response_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Session.SerializeToString,
            ),
            'CancelSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelSession,
                    request_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_service__pb2.SessionOperationRequest.FromString,
                    response_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Session.SerializeToString,
            ),
            'GetSession': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSession,
                    request_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_service__pb2.GetSessionRequest.FromString,
                    response_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Session.SerializeToString,
            ),
            'GetSessionView': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSessionView,
                    request_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_service__pb2.GetSessionRequest.FromString,
                    response_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.SessionView.SerializeToString,
            ),
            'GetSessionSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSessionSummary,
                    request_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_service__pb2.GetSessionRequest.FromString,
                    response_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.SessionSummary.SerializeToString,
            ),
            'ListSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessions,
                    request_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_service__pb2.ListSessionsRequest.FromString,
                    response_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_service__pb2.ListSessionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'questkeeper.v1.sessions.Sessions', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('questkeeper.v1.sessions.Sessions', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Sessions(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.v1.sessions.Sessions/CreateSession',
            qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.SessionInfo.SerializeToString,
            qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EditBasics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.v1.sessions.Sessions/EditBasics',
            qk__api__contracts_dot_grpc_dot_sessions_dot_service__pb2.EditBasicsRequest.SerializeToString,
            qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EditSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.v1.sessions.Sessions/EditSchedule',
            qk__api__contracts_dot_grpc_dot_sessions_dot_service__pb2.EditScheduleRequest.SerializeToString,
            qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EditCapacity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.v1.sessions.Sessions/EditCapacity',
            qk__api__contracts_dot_grpc_dot_sessions_dot_service__pb2.EditCapacityRequest.SerializeToString,
            qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EditOrganization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.v1.sessions.Sessions/EditOrganization',
            qk__api__contracts_dot_grpc_dot_sessions_dot_service__pb2.EditOrganizationRequest.SerializeToString,
            qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EditGM(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.v1.sessions.Sessions/EditGM',
            qk__api__contracts_dot_grpc_dot_sessions_dot_service__pb2.EditGMRequest.SerializeToString,
            qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.v1.sessions.Sessions/PublishSession',
            qk__api__contracts_dot_grpc_dot_sessions_dot_service__pb2.SessionOperationRequest.SerializeToString,
            qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.v1.sessions.Sessions/CancelSession',
            qk__api__contracts_dot_grpc_dot_sessions_dot_service__pb2.SessionOperationRequest.SerializeToString,
            qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.v1.sessions.Sessions/GetSession',
            qk__api__contracts_dot_grpc_dot_sessions_dot_service__pb2.GetSessionRequest.SerializeToString,
            qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSessionView(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.v1.sessions.Sessions/GetSessionView',
            qk__api__contracts_dot_grpc_dot_sessions_dot_service__pb2.GetSessionRequest.SerializeToString,
            qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.SessionView.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSessionSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.v1.sessions.Sessions/GetSessionSummary',
            qk__api__contracts_dot_grpc_dot_sessions_dot_service__pb2.GetSessionRequest.SerializeToString,
            qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.SessionSummary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.v1.sessions.Sessions/ListSessions',
            qk__api__contracts_dot_grpc_dot_sessions_dot_service__pb2.ListSessionsRequest.SerializeToString,
            qk__api__contracts_dot_grpc_dot_sessions_dot_service__pb2.ListSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SignupsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SignupToSession = channel.unary_unary(
                '/questkeeper.v1.sessions.Signups/SignupToSession',
                request_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.SignupInfo.SerializeToString,
                response_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Signup.FromString,
                _registered_method=True)
        self.SwitchReserve = channel.unary_unary(
                '/questkeeper.v1.sessions.Signups/SwitchReserve',
                request_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_service__pb2.SignupOperationRequest.SerializeToString,
                response_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Signup.FromString,
                _registered_method=True)
        self.SwitchMain = channel.unary_unary(
                '/questkeeper.v1.sessions.Signups/SwitchMain',
                request_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_service__pb2.SignupOperationRequest.SerializeToString,
                response_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Signup.FromString,
                _registered_method=True)
        self.SignOut = channel.unary_unary(
                '/questkeeper.v1.sessions.Signups/SignOut',
                request_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_service__pb2.SignupOperationRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.SetCharacter = channel.unary_unary(
                '/questkeeper.v1.sessions.Signups/SetCharacter',
                request_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_service__pb2.SetCharacterRequest.SerializeToString,
                response_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Signup.FromString,
                _registered_method=True)


class SignupsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SignupToSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SwitchReserve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SwitchMain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SignOut(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetCharacter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SignupsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SignupToSession': grpc.unary_unary_rpc_method_handler(
                    servicer.SignupToSession,
                    request_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.SignupInfo.FromString,
                    response_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Signup.SerializeToString,
            ),
            'SwitchReserve': grpc.unary_unary_rpc_method_handler(
                    servicer.SwitchReserve,
                    request_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_service__pb2.SignupOperationRequest.FromString,
                    response_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Signup.SerializeToString,
            ),
            'SwitchMain': grpc.unary_unary_rpc_method_handler(
                    servicer.SwitchMain,
                    request_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_service__pb2.SignupOperationRequest.FromString,
                    response_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Signup.SerializeToString,
            ),
            'SignOut': grpc.unary_unary_rpc_method_handler(
                    servicer.SignOut,
                    request_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_service__pb2.SignupOperationRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SetCharacter': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCharacter,
                    request_deserializer=qk__api__contracts_dot_grpc_dot_sessions_dot_service__pb2.SetCharacterRequest.FromString,
                    response_serializer=qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Signup.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'questkeeper.v1.sessions.Signups', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('questkeeper.v1.sessions.Signups', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Signups(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SignupToSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.v1.sessions.Signups/SignupToSession',
            qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.SignupInfo.SerializeToString,
            qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Signup.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SwitchReserve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.v1.sessions.Signups/SwitchReserve',
            qk__api__contracts_dot_grpc_dot_sessions_dot_service__pb2.SignupOperationRequest.SerializeToString,
            qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Signup.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SwitchMain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.v1.sessions.Signups/SwitchMain',
            qk__api__contracts_dot_grpc_dot_sessions_dot_service__pb2.SignupOperationRequest.SerializeToString,
            qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Signup.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SignOut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.v1.sessions.Signups/SignOut',
            qk__api__contracts_dot_grpc_dot_sessions_dot_service__pb2.SignupOperationRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetCharacter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.v1.sessions.Signups/SetCharacter',
            qk__api__contracts_dot_grpc_dot_sessions_dot_service__pb2.SetCharacterRequest.SerializeToString,
            qk__api__contracts_dot_grpc_dot_sessions_dot_models__pb2.Signup.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
