# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: qk_api_contracts/grpc/common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'qk_api_contracts/grpc/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"qk_api_contracts/grpc/common.proto\x12\x12questkeeper.common\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8f\x01\n\x0bRequestMeta\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x17\n\x0fidempotency_key\x18\x02 \x01(\t\x12\x18\n\x10tenant_server_id\x18\x03 \x01(\t\x12\x0f\n\x07user_id\x18\x04 \x01(\t\x12\x11\n\tapp_roles\x18\x05 \x03(\t\x12\x15\n\rif_none_match\x18\x06 \x01(\t\"4\n\x0bPageRequest\x12\x11\n\tpage_size\x18\x01 \x01(\x05\x12\x12\n\npage_token\x18\x02 \x01(\t\"3\n\x04Page\x12\x17\n\x0fnext_page_token\x18\x01 \x01(\t\x12\x12\n\ntotal_size\x18\x02 \x01(\r\"c\n\rVersionHeader\x12\x0f\n\x07version\x18\x01 \x01(\x04\x12\x11\n\tweak_etag\x18\x02 \x01(\t\x12.\n\nupdated_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestampb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'qk_api_contracts.grpc.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUESTMETA']._serialized_start=92
  _globals['_REQUESTMETA']._serialized_end=235
  _globals['_PAGEREQUEST']._serialized_start=237
  _globals['_PAGEREQUEST']._serialized_end=289
  _globals['_PAGE']._serialized_start=291
  _globals['_PAGE']._serialized_end=342
  _globals['_VERSIONHEADER']._serialized_start=344
  _globals['_VERSIONHEADER']._serialized_end=443
# @@protoc_insertion_point(module_scope)
