# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: servers.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'servers.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservers.proto\x12\x13questkeeper.servers\"-\n\x18GetServerSettingsRequest\x12\x11\n\tserver_id\x18\x01 \x01(\t\"\xa1\x02\n\x0eServerSettings\x12\x11\n\tserver_id\x18\x01 \x01(\t\x12\'\n\x1f\x64\x65\x66\x61ult_announcement_channel_id\x18\x02 \x01(\t\x12\x16\n\x0e\x64\x65\x66\x61ult_system\x18\x03 \x01(\t\x12 \n\x18\x64m_notifications_enabled\x18\x04 \x01(\x08\x12J\n\x0crole_mapping\x18\x05 \x03(\x0b\x32\x34.questkeeper.servers.ServerSettings.RoleMappingEntry\x12\x19\n\x11mentionable_roles\x18\x06 \x03(\t\x1a\x32\n\x10RoleMappingEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"*\n\x15GetRoleMappingRequest\x12\x11\n\tserver_id\x18\x01 \x01(\t\"\x90\x01\n\x0bRoleMapping\x12\x11\n\tserver_id\x18\x01 \x01(\t\x12>\n\x07mapping\x18\x02 \x03(\x0b\x32-.questkeeper.servers.RoleMapping.MappingEntry\x1a.\n\x0cMappingEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\x8b\x03\n\x07Servers\x12g\n\x11GetServerSettings\x12-.questkeeper.servers.GetServerSettingsRequest\x1a#.questkeeper.servers.ServerSettings\x12^\n\x12\x45\x64itServerSettings\x12#.questkeeper.servers.ServerSettings\x1a#.questkeeper.servers.ServerSettings\x12^\n\x0eGetRoleMapping\x12*.questkeeper.servers.GetRoleMappingRequest\x1a .questkeeper.servers.RoleMapping\x12W\n\x11UpdateRoleMapping\x12 .questkeeper.servers.RoleMapping\x1a .questkeeper.servers.RoleMappingb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'servers_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SERVERSETTINGS_ROLEMAPPINGENTRY']._loaded_options = None
  _globals['_SERVERSETTINGS_ROLEMAPPINGENTRY']._serialized_options = b'8\001'
  _globals['_ROLEMAPPING_MAPPINGENTRY']._loaded_options = None
  _globals['_ROLEMAPPING_MAPPINGENTRY']._serialized_options = b'8\001'
  _globals['_GETSERVERSETTINGSREQUEST']._serialized_start=38
  _globals['_GETSERVERSETTINGSREQUEST']._serialized_end=83
  _globals['_SERVERSETTINGS']._serialized_start=86
  _globals['_SERVERSETTINGS']._serialized_end=375
  _globals['_SERVERSETTINGS_ROLEMAPPINGENTRY']._serialized_start=325
  _globals['_SERVERSETTINGS_ROLEMAPPINGENTRY']._serialized_end=375
  _globals['_GETROLEMAPPINGREQUEST']._serialized_start=377
  _globals['_GETROLEMAPPINGREQUEST']._serialized_end=419
  _globals['_ROLEMAPPING']._serialized_start=422
  _globals['_ROLEMAPPING']._serialized_end=566
  _globals['_ROLEMAPPING_MAPPINGENTRY']._serialized_start=520
  _globals['_ROLEMAPPING_MAPPINGENTRY']._serialized_end=566
  _globals['_SERVERS']._serialized_start=569
  _globals['_SERVERS']._serialized_end=964
# @@protoc_insertion_point(module_scope)
