# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import servers_pb2 as servers__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in servers_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ServersStub(object):
    """--- service ---
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetServerSettings = channel.unary_unary(
                '/questkeeper.servers.Servers/GetServerSettings',
                request_serializer=servers__pb2.GetServerSettingsRequest.SerializeToString,
                response_deserializer=servers__pb2.ServerSettings.FromString,
                _registered_method=True)
        self.EditServerSettings = channel.unary_unary(
                '/questkeeper.servers.Servers/EditServerSettings',
                request_serializer=servers__pb2.ServerSettings.SerializeToString,
                response_deserializer=servers__pb2.ServerSettings.FromString,
                _registered_method=True)
        self.GetRoleMapping = channel.unary_unary(
                '/questkeeper.servers.Servers/GetRoleMapping',
                request_serializer=servers__pb2.GetRoleMappingRequest.SerializeToString,
                response_deserializer=servers__pb2.RoleMapping.FromString,
                _registered_method=True)
        self.UpdateRoleMapping = channel.unary_unary(
                '/questkeeper.servers.Servers/UpdateRoleMapping',
                request_serializer=servers__pb2.RoleMapping.SerializeToString,
                response_deserializer=servers__pb2.RoleMapping.FromString,
                _registered_method=True)


class ServersServicer(object):
    """--- service ---
    """

    def GetServerSettings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditServerSettings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRoleMapping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRoleMapping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServersServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetServerSettings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerSettings,
                    request_deserializer=servers__pb2.GetServerSettingsRequest.FromString,
                    response_serializer=servers__pb2.ServerSettings.SerializeToString,
            ),
            'EditServerSettings': grpc.unary_unary_rpc_method_handler(
                    servicer.EditServerSettings,
                    request_deserializer=servers__pb2.ServerSettings.FromString,
                    response_serializer=servers__pb2.ServerSettings.SerializeToString,
            ),
            'GetRoleMapping': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRoleMapping,
                    request_deserializer=servers__pb2.GetRoleMappingRequest.FromString,
                    response_serializer=servers__pb2.RoleMapping.SerializeToString,
            ),
            'UpdateRoleMapping': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRoleMapping,
                    request_deserializer=servers__pb2.RoleMapping.FromString,
                    response_serializer=servers__pb2.RoleMapping.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'questkeeper.servers.Servers', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('questkeeper.servers.Servers', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Servers(object):
    """--- service ---
    """

    @staticmethod
    def GetServerSettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.servers.Servers/GetServerSettings',
            servers__pb2.GetServerSettingsRequest.SerializeToString,
            servers__pb2.ServerSettings.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EditServerSettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.servers.Servers/EditServerSettings',
            servers__pb2.ServerSettings.SerializeToString,
            servers__pb2.ServerSettings.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRoleMapping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.servers.Servers/GetRoleMapping',
            servers__pb2.GetRoleMappingRequest.SerializeToString,
            servers__pb2.RoleMapping.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateRoleMapping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.servers.Servers/UpdateRoleMapping',
            servers__pb2.RoleMapping.SerializeToString,
            servers__pb2.RoleMapping.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
