# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: worker_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'worker_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from sessions import models_pb2 as sessions_dot_models__pb2
from events import models_pb2 as events_dot_models__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14worker_service.proto\x12\x12questkeeper.worker\x1a\x15sessions/models.proto\x1a\x13\x65vents/models.proto\"W\n\x13SetMessageIdRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x12\n\nmessage_id\x18\x02 \x01(\t\x12\x18\n\x10\x65xpected_version\x18\x03 \x01(\x04\x32\xce\x01\n\x06Worker\x12\x64\n\x13SetSessionMessageId\x12\'.questkeeper.worker.SetMessageIdRequest\x1a$.questkeeper.sessions.models.Session\x12^\n\x11SetEventMessageId\x12\'.questkeeper.worker.SetMessageIdRequest\x1a .questkeeper.events.models.Eventb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'worker_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SETMESSAGEIDREQUEST']._serialized_start=88
  _globals['_SETMESSAGEIDREQUEST']._serialized_end=175
  _globals['_WORKER']._serialized_start=178
  _globals['_WORKER']._serialized_end=384
# @@protoc_insertion_point(module_scope)
