# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import characters_pb2 as characters__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in characters_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CharacterServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListCharacters = channel.unary_unary(
                '/questkeeper.characters.CharacterService/ListCharacters',
                request_serializer=characters__pb2.ListCharactersRequest.SerializeToString,
                response_deserializer=characters__pb2.ListCharactersResponse.FromString,
                _registered_method=True)
        self.CreateCharacter = channel.unary_unary(
                '/questkeeper.characters.CharacterService/CreateCharacter',
                request_serializer=characters__pb2.CreateCharacterRequest.SerializeToString,
                response_deserializer=characters__pb2.Character.FromString,
                _registered_method=True)
        self.GetCharacter = channel.unary_unary(
                '/questkeeper.characters.CharacterService/GetCharacter',
                request_serializer=characters__pb2.GetCharacterRequest.SerializeToString,
                response_deserializer=characters__pb2.CharacterResponse.FromString,
                _registered_method=True)
        self.UpdateCharacter = channel.unary_unary(
                '/questkeeper.characters.CharacterService/UpdateCharacter',
                request_serializer=characters__pb2.UpdateCharacterRequest.SerializeToString,
                response_deserializer=characters__pb2.CharacterResponse.FromString,
                _registered_method=True)
        self.DeleteCharacter = channel.unary_unary(
                '/questkeeper.characters.CharacterService/DeleteCharacter',
                request_serializer=characters__pb2.DeleteCharacterRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetCharacterHistory = channel.unary_unary(
                '/questkeeper.characters.CharacterService/GetCharacterHistory',
                request_serializer=characters__pb2.GetCharacterHistoryRequest.SerializeToString,
                response_deserializer=characters__pb2.GetCharacterHistoryResponse.FromString,
                _registered_method=True)


class CharacterServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListCharacters(self, request, context):
        """GET /characters/
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCharacter(self, request, context):
        """POST /characters/
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCharacter(self, request, context):
        """GET /characters/{character_id}/
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCharacter(self, request, context):
        """PATCH /characters/{character_id}/
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCharacter(self, request, context):
        """DELETE /characters/{character_id}/
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCharacterHistory(self, request, context):
        """GET /characters/{character_id}/history
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CharacterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListCharacters': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCharacters,
                    request_deserializer=characters__pb2.ListCharactersRequest.FromString,
                    response_serializer=characters__pb2.ListCharactersResponse.SerializeToString,
            ),
            'CreateCharacter': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCharacter,
                    request_deserializer=characters__pb2.CreateCharacterRequest.FromString,
                    response_serializer=characters__pb2.Character.SerializeToString,
            ),
            'GetCharacter': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCharacter,
                    request_deserializer=characters__pb2.GetCharacterRequest.FromString,
                    response_serializer=characters__pb2.CharacterResponse.SerializeToString,
            ),
            'UpdateCharacter': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCharacter,
                    request_deserializer=characters__pb2.UpdateCharacterRequest.FromString,
                    response_serializer=characters__pb2.CharacterResponse.SerializeToString,
            ),
            'DeleteCharacter': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCharacter,
                    request_deserializer=characters__pb2.DeleteCharacterRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetCharacterHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCharacterHistory,
                    request_deserializer=characters__pb2.GetCharacterHistoryRequest.FromString,
                    response_serializer=characters__pb2.GetCharacterHistoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'questkeeper.characters.CharacterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('questkeeper.characters.CharacterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CharacterService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListCharacters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.characters.CharacterService/ListCharacters',
            characters__pb2.ListCharactersRequest.SerializeToString,
            characters__pb2.ListCharactersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateCharacter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.characters.CharacterService/CreateCharacter',
            characters__pb2.CreateCharacterRequest.SerializeToString,
            characters__pb2.Character.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCharacter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.characters.CharacterService/GetCharacter',
            characters__pb2.GetCharacterRequest.SerializeToString,
            characters__pb2.CharacterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateCharacter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.characters.CharacterService/UpdateCharacter',
            characters__pb2.UpdateCharacterRequest.SerializeToString,
            characters__pb2.CharacterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCharacter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.characters.CharacterService/DeleteCharacter',
            characters__pb2.DeleteCharacterRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCharacterHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.characters.CharacterService/GetCharacterHistory',
            characters__pb2.GetCharacterHistoryRequest.SerializeToString,
            characters__pb2.GetCharacterHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
