# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: enums.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'enums.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x65nums.proto\x12\x11questkeeper.enums*X\n\nSignupRole\x12\x1b\n\x17SIGNUP_ROLE_UNSPECIFIED\x10\x00\x12\x14\n\x10SIGNUP_ROLE_MAIN\x10\x01\x12\x17\n\x13SIGNUP_ROLE_RESERVE\x10\x02*7\n\x07\x41ppRole\x12\x0e\n\nROLE_ADMIN\x10\x00\x12\x0b\n\x07ROLE_GM\x10\x01\x12\x0f\n\x0bROLE_PLAYER\x10\x02*I\n\nGameSystem\x12\x11\n\rPATHFINDER_1E\x10\x00\x12\x11\n\rPATHFINDER_2E\x10\x01\x12\n\n\x06\x44ND_5E\x10\x02\x12\t\n\x05\x44SA_5\x10\x03*\'\n\x04Seat\x12\r\n\tSEAT_MAIN\x10\x00\x12\x10\n\x0cSEAT_RESERVE\x10\x01*\x80\x01\n\rSessionStatus\x12\x17\n\x13SESSION_UNSPECIFIED\x10\x00\x12\x11\n\rSESSION_DRAFT\x10\x01\x12\x15\n\x11SESSION_PUBLISHED\x10\x02\x12\x15\n\x11SESSION_CANCELLED\x10\x03\x12\x15\n\x11SESSION_COMPLETED\x10\x04*t\n\x0b\x45ventStatus\x12\x15\n\x11\x45VENT_UNSPECIFIED\x10\x00\x12\x0f\n\x0b\x45VENT_DRAFT\x10\x01\x12\x13\n\x0f\x45VENT_PUBLISHED\x10\x02\x12\x13\n\x0f\x45VENT_CANCELLED\x10\x03\x12\x13\n\x0f\x45VENT_COMPLETED\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'enums_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SIGNUPROLE']._serialized_start=34
  _globals['_SIGNUPROLE']._serialized_end=122
  _globals['_APPROLE']._serialized_start=124
  _globals['_APPROLE']._serialized_end=179
  _globals['_GAMESYSTEM']._serialized_start=181
  _globals['_GAMESYSTEM']._serialized_end=254
  _globals['_SEAT']._serialized_start=256
  _globals['_SEAT']._serialized_end=295
  _globals['_SESSIONSTATUS']._serialized_start=298
  _globals['_SESSIONSTATUS']._serialized_end=426
  _globals['_EVENTSTATUS']._serialized_start=428
  _globals['_EVENTSTATUS']._serialized_end=544
# @@protoc_insertion_point(module_scope)
