# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import events_pb2 as events__pb2
import sessions_pb2 as sessions__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in events_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EventServiceStub(object):
    """---------- Service ----------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListEvents = channel.unary_unary(
                '/questkeeper.events.EventService/ListEvents',
                request_serializer=events__pb2.ListEventsRequest.SerializeToString,
                response_deserializer=events__pb2.ListEventsResponse.FromString,
                _registered_method=True)
        self.CreateEvent = channel.unary_unary(
                '/questkeeper.events.EventService/CreateEvent',
                request_serializer=events__pb2.CreateEventRequest.SerializeToString,
                response_deserializer=events__pb2.EventResponse.FromString,
                _registered_method=True)
        self.GetEvent = channel.unary_unary(
                '/questkeeper.events.EventService/GetEvent',
                request_serializer=events__pb2.GetEventRequest.SerializeToString,
                response_deserializer=events__pb2.EventResponse.FromString,
                _registered_method=True)
        self.UpdateEvent = channel.unary_unary(
                '/questkeeper.events.EventService/UpdateEvent',
                request_serializer=events__pb2.UpdateEventRequest.SerializeToString,
                response_deserializer=events__pb2.EventResponse.FromString,
                _registered_method=True)
        self.DeleteEvent = channel.unary_unary(
                '/questkeeper.events.EventService/DeleteEvent',
                request_serializer=events__pb2.DeleteEventRequest.SerializeToString,
                response_deserializer=events__pb2.EventResponse.FromString,
                _registered_method=True)
        self.PublishEvent = channel.unary_unary(
                '/questkeeper.events.EventService/PublishEvent',
                request_serializer=events__pb2.PublishEventRequest.SerializeToString,
                response_deserializer=events__pb2.PublishEventResponse.FromString,
                _registered_method=True)
        self.CancelEvent = channel.unary_unary(
                '/questkeeper.events.EventService/CancelEvent',
                request_serializer=events__pb2.CancelEventRequest.SerializeToString,
                response_deserializer=events__pb2.EventResponse.FromString,
                _registered_method=True)
        self.CreateSession = channel.unary_unary(
                '/questkeeper.events.EventService/CreateSession',
                request_serializer=sessions__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=sessions__pb2.SessionResponse.FromString,
                _registered_method=True)
        self.SetMessageId = channel.unary_unary(
                '/questkeeper.events.EventService/SetMessageId',
                request_serializer=events__pb2.SetMessageIdRequest.SerializeToString,
                response_deserializer=events__pb2.EventResponse.FromString,
                _registered_method=True)


class EventServiceServicer(object):
    """---------- Service ----------
    """

    def ListEvents(self, request, context):
        """GET /events/
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateEvent(self, request, context):
        """POST /events/
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEvent(self, request, context):
        """GET /events/{event_id}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateEvent(self, request, context):
        """PATCH /events/{event_id}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteEvent(self, request, context):
        """DELETE /events/{event_id}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishEvent(self, request, context):
        """POST /events/{event_id}:publish
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelEvent(self, request, context):
        """POST /events/{event_id}:cancel
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSession(self, request, context):
        """POST /events/{event_id}/sessions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMessageId(self, request, context):
        """worker
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEvents,
                    request_deserializer=events__pb2.ListEventsRequest.FromString,
                    response_serializer=events__pb2.ListEventsResponse.SerializeToString,
            ),
            'CreateEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEvent,
                    request_deserializer=events__pb2.CreateEventRequest.FromString,
                    response_serializer=events__pb2.EventResponse.SerializeToString,
            ),
            'GetEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEvent,
                    request_deserializer=events__pb2.GetEventRequest.FromString,
                    response_serializer=events__pb2.EventResponse.SerializeToString,
            ),
            'UpdateEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateEvent,
                    request_deserializer=events__pb2.UpdateEventRequest.FromString,
                    response_serializer=events__pb2.EventResponse.SerializeToString,
            ),
            'DeleteEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteEvent,
                    request_deserializer=events__pb2.DeleteEventRequest.FromString,
                    response_serializer=events__pb2.EventResponse.SerializeToString,
            ),
            'PublishEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishEvent,
                    request_deserializer=events__pb2.PublishEventRequest.FromString,
                    response_serializer=events__pb2.PublishEventResponse.SerializeToString,
            ),
            'CancelEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelEvent,
                    request_deserializer=events__pb2.CancelEventRequest.FromString,
                    response_serializer=events__pb2.EventResponse.SerializeToString,
            ),
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=sessions__pb2.CreateSessionRequest.FromString,
                    response_serializer=sessions__pb2.SessionResponse.SerializeToString,
            ),
            'SetMessageId': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMessageId,
                    request_deserializer=events__pb2.SetMessageIdRequest.FromString,
                    response_serializer=events__pb2.EventResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'questkeeper.events.EventService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('questkeeper.events.EventService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EventService(object):
    """---------- Service ----------
    """

    @staticmethod
    def ListEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.events.EventService/ListEvents',
            events__pb2.ListEventsRequest.SerializeToString,
            events__pb2.ListEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.events.EventService/CreateEvent',
            events__pb2.CreateEventRequest.SerializeToString,
            events__pb2.EventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.events.EventService/GetEvent',
            events__pb2.GetEventRequest.SerializeToString,
            events__pb2.EventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.events.EventService/UpdateEvent',
            events__pb2.UpdateEventRequest.SerializeToString,
            events__pb2.EventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.events.EventService/DeleteEvent',
            events__pb2.DeleteEventRequest.SerializeToString,
            events__pb2.EventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.events.EventService/PublishEvent',
            events__pb2.PublishEventRequest.SerializeToString,
            events__pb2.PublishEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.events.EventService/CancelEvent',
            events__pb2.CancelEventRequest.SerializeToString,
            events__pb2.EventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.events.EventService/CreateSession',
            sessions__pb2.CreateSessionRequest.SerializeToString,
            sessions__pb2.SessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetMessageId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.events.EventService/SetMessageId',
            events__pb2.SetMessageIdRequest.SerializeToString,
            events__pb2.EventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
