# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: meta.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'meta.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nmeta.proto\x12\x10questkeeper.meta\"\x0f\n\rHealthRequest\" \n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x11\n\x0fVersionsRequest\"\x8d\x01\n\x10VersionsResponse\x12\x46\n\ncomponents\x18\x01 \x03(\x0b\x32\x32.questkeeper.meta.VersionsResponse.ComponentsEntry\x1a\x31\n\x0f\x43omponentsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\xad\x01\n\x0bMetaService\x12K\n\x06Health\x12\x1f.questkeeper.meta.HealthRequest\x1a .questkeeper.meta.HealthResponse\x12Q\n\x08Versions\x12!.questkeeper.meta.VersionsRequest\x1a\".questkeeper.meta.VersionsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'meta_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VERSIONSRESPONSE_COMPONENTSENTRY']._loaded_options = None
  _globals['_VERSIONSRESPONSE_COMPONENTSENTRY']._serialized_options = b'8\001'
  _globals['_HEALTHREQUEST']._serialized_start=32
  _globals['_HEALTHREQUEST']._serialized_end=47
  _globals['_HEALTHRESPONSE']._serialized_start=49
  _globals['_HEALTHRESPONSE']._serialized_end=81
  _globals['_VERSIONSREQUEST']._serialized_start=83
  _globals['_VERSIONSREQUEST']._serialized_end=100
  _globals['_VERSIONSRESPONSE']._serialized_start=103
  _globals['_VERSIONSRESPONSE']._serialized_end=244
  _globals['_VERSIONSRESPONSE_COMPONENTSENTRY']._serialized_start=195
  _globals['_VERSIONSRESPONSE_COMPONENTSENTRY']._serialized_end=244
  _globals['_METASERVICE']._serialized_start=247
  _globals['_METASERVICE']._serialized_end=420
# @@protoc_insertion_point(module_scope)
