# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sessions_pb2 as sessions__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sessions_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SessionServiceStub(object):
    """---------- Service ----------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListSessions = channel.unary_unary(
                '/questkeeper.sessions.SessionService/ListSessions',
                request_serializer=sessions__pb2.ListSessionsRequest.SerializeToString,
                response_deserializer=sessions__pb2.ListSessionsResponse.FromString,
                _registered_method=True)
        self.CreateSession = channel.unary_unary(
                '/questkeeper.sessions.SessionService/CreateSession',
                request_serializer=sessions__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=sessions__pb2.SessionResponse.FromString,
                _registered_method=True)
        self.GetSession = channel.unary_unary(
                '/questkeeper.sessions.SessionService/GetSession',
                request_serializer=sessions__pb2.GetSessionRequest.SerializeToString,
                response_deserializer=sessions__pb2.SessionResponse.FromString,
                _registered_method=True)
        self.UpdateSession = channel.unary_unary(
                '/questkeeper.sessions.SessionService/UpdateSession',
                request_serializer=sessions__pb2.UpdateSessionRequest.SerializeToString,
                response_deserializer=sessions__pb2.SessionResponse.FromString,
                _registered_method=True)
        self.DeleteSession = channel.unary_unary(
                '/questkeeper.sessions.SessionService/DeleteSession',
                request_serializer=sessions__pb2.DeleteSessionRequest.SerializeToString,
                response_deserializer=sessions__pb2.SessionResponse.FromString,
                _registered_method=True)
        self.PublishSession = channel.unary_unary(
                '/questkeeper.sessions.SessionService/PublishSession',
                request_serializer=sessions__pb2.PublishSessionRequest.SerializeToString,
                response_deserializer=sessions__pb2.PublishSessionResponse.FromString,
                _registered_method=True)
        self.CancelSession = channel.unary_unary(
                '/questkeeper.sessions.SessionService/CancelSession',
                request_serializer=sessions__pb2.CancelSessionRequest.SerializeToString,
                response_deserializer=sessions__pb2.SessionResponse.FromString,
                _registered_method=True)
        self.SetMessageId = channel.unary_unary(
                '/questkeeper.sessions.SessionService/SetMessageId',
                request_serializer=sessions__pb2.SetMessageIdRequest.SerializeToString,
                response_deserializer=sessions__pb2.SessionResponse.FromString,
                _registered_method=True)


class SessionServiceServicer(object):
    """---------- Service ----------
    """

    def ListSessions(self, request, context):
        """GET /sessions/
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSession(self, request, context):
        """POST /sessions/
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSession(self, request, context):
        """GET /sessions/{session_id}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSession(self, request, context):
        """PATCH /sessions/{session_id}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSession(self, request, context):
        """DELETE /sessions/{session_id}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishSession(self, request, context):
        """POST /sessions/{session_id}:publish
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelSession(self, request, context):
        """POST /sessions/{session_id}:cancel
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMessageId(self, request, context):
        """worker
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SessionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessions,
                    request_deserializer=sessions__pb2.ListSessionsRequest.FromString,
                    response_serializer=sessions__pb2.ListSessionsResponse.SerializeToString,
            ),
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=sessions__pb2.CreateSessionRequest.FromString,
                    response_serializer=sessions__pb2.SessionResponse.SerializeToString,
            ),
            'GetSession': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSession,
                    request_deserializer=sessions__pb2.GetSessionRequest.FromString,
                    response_serializer=sessions__pb2.SessionResponse.SerializeToString,
            ),
            'UpdateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSession,
                    request_deserializer=sessions__pb2.UpdateSessionRequest.FromString,
                    response_serializer=sessions__pb2.SessionResponse.SerializeToString,
            ),
            'DeleteSession': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSession,
                    request_deserializer=sessions__pb2.DeleteSessionRequest.FromString,
                    response_serializer=sessions__pb2.SessionResponse.SerializeToString,
            ),
            'PublishSession': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishSession,
                    request_deserializer=sessions__pb2.PublishSessionRequest.FromString,
                    response_serializer=sessions__pb2.PublishSessionResponse.SerializeToString,
            ),
            'CancelSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelSession,
                    request_deserializer=sessions__pb2.CancelSessionRequest.FromString,
                    response_serializer=sessions__pb2.SessionResponse.SerializeToString,
            ),
            'SetMessageId': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMessageId,
                    request_deserializer=sessions__pb2.SetMessageIdRequest.FromString,
                    response_serializer=sessions__pb2.SessionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'questkeeper.sessions.SessionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('questkeeper.sessions.SessionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SessionService(object):
    """---------- Service ----------
    """

    @staticmethod
    def ListSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.sessions.SessionService/ListSessions',
            sessions__pb2.ListSessionsRequest.SerializeToString,
            sessions__pb2.ListSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.sessions.SessionService/CreateSession',
            sessions__pb2.CreateSessionRequest.SerializeToString,
            sessions__pb2.SessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.sessions.SessionService/GetSession',
            sessions__pb2.GetSessionRequest.SerializeToString,
            sessions__pb2.SessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.sessions.SessionService/UpdateSession',
            sessions__pb2.UpdateSessionRequest.SerializeToString,
            sessions__pb2.SessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.sessions.SessionService/DeleteSession',
            sessions__pb2.DeleteSessionRequest.SerializeToString,
            sessions__pb2.SessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.sessions.SessionService/PublishSession',
            sessions__pb2.PublishSessionRequest.SerializeToString,
            sessions__pb2.PublishSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.sessions.SessionService/CancelSession',
            sessions__pb2.CancelSessionRequest.SerializeToString,
            sessions__pb2.SessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetMessageId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.sessions.SessionService/SetMessageId',
            sessions__pb2.SetMessageIdRequest.SerializeToString,
            sessions__pb2.SessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
