# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import signups_pb2 as signups__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in signups_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SignupServiceStub(object):
    """---------- Service ----------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListSignups = channel.unary_unary(
                '/questkeeper.signups.SignupService/ListSignups',
                request_serializer=signups__pb2.ListSignupsRequest.SerializeToString,
                response_deserializer=signups__pb2.ListSignupsResponse.FromString,
                _registered_method=True)
        self.CreateSignup = channel.unary_unary(
                '/questkeeper.signups.SignupService/CreateSignup',
                request_serializer=signups__pb2.CreateSignupRequest.SerializeToString,
                response_deserializer=signups__pb2.SignupResponse.FromString,
                _registered_method=True)
        self.GetSignup = channel.unary_unary(
                '/questkeeper.signups.SignupService/GetSignup',
                request_serializer=signups__pb2.GetSignupRequest.SerializeToString,
                response_deserializer=signups__pb2.SignupResponse.FromString,
                _registered_method=True)
        self.UpdateSignup = channel.unary_unary(
                '/questkeeper.signups.SignupService/UpdateSignup',
                request_serializer=signups__pb2.UpdateSignupRequest.SerializeToString,
                response_deserializer=signups__pb2.SignupResponse.FromString,
                _registered_method=True)
        self.DeleteSignup = channel.unary_unary(
                '/questkeeper.signups.SignupService/DeleteSignup',
                request_serializer=signups__pb2.DeleteSignupRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class SignupServiceServicer(object):
    """---------- Service ----------
    """

    def ListSignups(self, request, context):
        """GET /sessions/{signup_id}/signups
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSignup(self, request, context):
        """POST /sessions/{signup_id}/signups
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSignup(self, request, context):
        """GET /sessions/{signup_id}/signups/{user_id}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSignup(self, request, context):
        """PATCH /sessions/{signup_id}/signups/{user_id}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSignup(self, request, context):
        """DELETE /sessions/{signup_id}/signups/{user_id}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SignupServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListSignups': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSignups,
                    request_deserializer=signups__pb2.ListSignupsRequest.FromString,
                    response_serializer=signups__pb2.ListSignupsResponse.SerializeToString,
            ),
            'CreateSignup': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSignup,
                    request_deserializer=signups__pb2.CreateSignupRequest.FromString,
                    response_serializer=signups__pb2.SignupResponse.SerializeToString,
            ),
            'GetSignup': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSignup,
                    request_deserializer=signups__pb2.GetSignupRequest.FromString,
                    response_serializer=signups__pb2.SignupResponse.SerializeToString,
            ),
            'UpdateSignup': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSignup,
                    request_deserializer=signups__pb2.UpdateSignupRequest.FromString,
                    response_serializer=signups__pb2.SignupResponse.SerializeToString,
            ),
            'DeleteSignup': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSignup,
                    request_deserializer=signups__pb2.DeleteSignupRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'questkeeper.signups.SignupService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('questkeeper.signups.SignupService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SignupService(object):
    """---------- Service ----------
    """

    @staticmethod
    def ListSignups(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.signups.SignupService/ListSignups',
            signups__pb2.ListSignupsRequest.SerializeToString,
            signups__pb2.ListSignupsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSignup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.signups.SignupService/CreateSignup',
            signups__pb2.CreateSignupRequest.SerializeToString,
            signups__pb2.SignupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSignup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.signups.SignupService/GetSignup',
            signups__pb2.GetSignupRequest.SerializeToString,
            signups__pb2.SignupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSignup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.signups.SignupService/UpdateSignup',
            signups__pb2.UpdateSignupRequest.SerializeToString,
            signups__pb2.SignupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSignup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.signups.SignupService/DeleteSignup',
            signups__pb2.DeleteSignupRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
