syntax = "proto3";

package questkeeper.characters;

import "google/protobuf/timestamp.proto";
import "google/protobuf/empty.proto";
import "common.proto";
import "enums.proto";

service CharacterService {
  // GET /characters/
  rpc ListCharacters (ListCharactersRequest) returns (ListCharactersResponse);

  // POST /characters/
  rpc CreateCharacter (CreateCharacterRequest) returns (Character);
  // GET /characters/{character_id}/
  rpc GetCharacter (GetCharacterRequest) returns (CharacterResponse);
  // PATCH /characters/{character_id}/
  rpc UpdateCharacter (UpdateCharacterRequest) returns (CharacterResponse);
  // DELETE /characters/{character_id}/
  rpc DeleteCharacter (DeleteCharacterRequest) returns (google.protobuf.Empty);

  // GET /characters/{character_id}/history
  rpc GetCharacterHistory (GetCharacterHistoryRequest) returns (GetCharacterHistoryResponse);
}

// create

message CreateCharacterRequest {
  common.RequestMeta meta = 1;
  Character character = 2;
}

// read

message GetCharacterRequest {
  common.RequestMeta meta = 1;
  string character_id = 2;
}

// delete

message DeleteCharacterRequest {
  common.RequestMeta meta = 1;
  string character_id = 2;
}

// update

message UpdateCharacterRequest {
  common.RequestMeta meta = 1;
  string character_id = 2;
  UpdateCharacter update = 3;
}

message UpdateCharacter {
  optional string name = 1;
  optional string race = 2;
  optional string class = 3;
  optional int32 level = 4;
  optional string notes = 5;
}

// get history

message GetCharacterHistoryRequest {
  common.RequestMeta meta = 1;
  string character_id = 2;
}

message GetCharacterHistoryResponse {
  repeated CharacterHistoryEntry history = 1;
}

message CharacterHistoryEntry {
  string session_id = 1;
  string event_id = 2;
}

// get list

message ListCharactersRequest {
  common.RequestMeta meta = 1;
  common.PageRequest page = 2;
  int64 user_id = 3;
}

message ListCharactersResponse {
  repeated Character characters = 1;
  common.Page page = 2;
}

// models
message Character {
  string character_id = 1;
  int64 user_id = 2;
  enums.GameSystem system = 3;

  int32 level = 4;
  string name = 5;
  string race = 6;
  string class = 7;
  string subclass = 8;
  string notes = 9;

  google.protobuf.Timestamp created_at = 10;
  google.protobuf.Timestamp updated_at = 11;
}

message CharacterResponse {
  Character character = 1;
  common.VersionHeader version = 2;
}
