syntax = "proto3";

package questkeeper.servers;

import "common.proto";

// --- service ---
service ServersService {
  rpc GetServerSettings(GetServerSettingsRequest) returns (ServerSettingsResponse);
  rpc EditServerSettings(EditServerSettingsRequest) returns (ServerSettingsResponse);

  rpc GetRoleMapping(GetRoleMappingRequest) returns (RoleMappingResponse);
  rpc UpdateRoleMapping(UpdateRoleMappingRequest) returns (RoleMappingResponse);
}

// --- server settings ---
// requests

message GetServerSettingsRequest {
  common.RequestMeta meta = 1;
  string server_id = 2;
}

message EditServerSettingsRequest {
  common.RequestMeta meta = 1;
  string server_id = 2;
  ServerSettings update = 3;
}

// models

message ServerSettings {
  string server_id = 1;
  string default_announcement_channel_id = 2;
  string default_system = 3;
  bool dm_notifications_enabled = 4;
  map<string, string> role_mapping = 5;
  repeated string mentionable_roles = 6;
}

message ServerSettingsResponse {
  ServerSettings settings = 1;
  common.VersionHeader version = 2;
}

// --- roles mapping ---
// requests

message GetRoleMappingRequest {
  string server_id = 1;
}

message UpdateRoleMappingRequest {
  string server_id = 1;
  map<string, string> mapping = 2;
}

// model

message RoleMappingResponse {
  string server_id = 1;
  map<string, string> mapping = 2;
  common.VersionHeader version = 3;
}