syntax = "proto3";

package questkeeper.characters;

import "qk_api_contracts/grpc/common.proto";
import "qk_api_contracts/grpc/characters/models.proto";

// --- queries service (read models/projections)
service CharactersQuery {
  rpc GetCharacter(CharacterIdRequest) returns (models.Character);
  rpc ListCharacters(ListCharactersRequest) returns (ListCharactersResponse);
  rpc GetCharacterPlayHistory(CharacterIdRequest) returns (PlayHistoryResponse);
}

// --- requests ---

message CharacterIdRequest {
  string character_id = 1;
}

message ListCharactersRequest {
  int64 user_id = 1;
  string system = 2;

  common.PageRequest page = 6;
}

message ListCharactersResponse {
  repeated models.Character items = 1;
  common.Page page = 2;
}

message PlayHistoryResponse {
  repeated models.PlayRecord records = 1;
  string character_id = 2;

  common.Page page = 3;
}