syntax = "proto3";

package questkeeper.v1.characters;

import "google/protobuf/empty.proto";
import "qk_api_contracts/grpc/common.proto";
import "qk_api_contracts/grpc/characters/models.proto";


service Characters {
  // commands
  rpc CreateCharacter(models.CharacterInfo) returns (models.Character);
  rpc EditName(EditNameRequest) returns (models.Character);
  rpc EditSystem(EditSystemRequest) returns (models.Character);
  rpc EditClass(EditClassRequest) returns (models.Character);
  rpc EditRace(EditRaceRequest) returns (models.Character);
  rpc EditLevel(EditLevelRequest) returns (models.Character);
  rpc EditNotes(EditNotesRequest) returns (models.Character);
  rpc DeleteCharacter(DeleteCharacterRequest) returns (google.protobuf.Empty);

  // queries
  rpc GetCharacter(CharacterIdRequest) returns (models.Character);
  rpc ListCharacters(ListCharactersRequest) returns (ListCharactersResponse);
  rpc GetCharacterPlayHistory(CharacterIdRequest) returns (PlayHistoryResponse);

}

// --- commands ---

// edit

message EditNameRequest {
  string character_id = 1;
  string name = 2;

  uint64 expected_version = 3;
}

message EditSystemRequest {
  string character_id = 1;
  string game_system = 2;

  uint64 expected_version = 3;
}

message EditClassRequest {
  string character_id = 1;
  string class = 2;
  string subclass = 3;

  uint64 expected_version = 4;
}

message EditRaceRequest {
  string character_id = 1;
  string race = 2;

  uint64 expected_version = 3;
}

message EditLevelRequest {
  string character_id = 1;
  int32 level = 2;

  uint64 expected_version = 3;
}

message EditNotesRequest {
  string character_id = 1;
  string notes = 2;

  uint64 expected_version = 3;
}

message DeleteCharacterRequest {
  string character_id = 1;

  uint64 expected_version = 2;
}


// --- queries ---

message CharacterIdRequest {
  string character_id = 1;
}

message ListCharactersRequest {
  int64 user_id = 1;
  string system = 2;

  common.PageRequest page = 6;
}

message ListCharactersResponse {
  repeated models.Character items = 1;
  common.Page page = 2;
}

message PlayHistoryResponse {
  repeated models.PlayRecord records = 1;
  string character_id = 2;

  common.Page page = 3;
}