[build-system]
requires = ["hatchling>=1.25"]
build-backend = "hatchling.build"

[tool.uv.workspace]
members = [
  "services/api_gateway",
  "services/domain",
  "services/worker",
  "services/bot",
  "libs/render_sdk",
  "libs/api_contracts",
]

[tool.ruff]
extend-select = ["I", "UP", "RUF", "TID"]
line-length = 120
target-version = "py313"
ignore = [
    "D100",   # ignore missing docs
]

[tool.ruff.lint]
fixable = ["ALL"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.mypy]
python_version = "3.13"
strict = true
disallow_untyped_defs = True
ignore_missing_imports = True
no_implicit_optional = True
check_untyped_defs = True
warn_return_any = True