# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from events import commands_service_pb2 as events_dot_commands__service__pb2
from events import models_pb2 as events_dot_models__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in events/commands_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EventsCommandsStub(object):
    """--- domain commands service (write) ---
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateEvent = channel.unary_unary(
                '/questkeeper.events.commands_service.EventsCommands/CreateEvent',
                request_serializer=events_dot_models__pb2.EventInfo.SerializeToString,
                response_deserializer=events_dot_models__pb2.Event.FromString,
                _registered_method=True)
        self.EditBasics = channel.unary_unary(
                '/questkeeper.events.commands_service.EventsCommands/EditBasics',
                request_serializer=events_dot_commands__service__pb2.EditBasicsRequest.SerializeToString,
                response_deserializer=events_dot_models__pb2.Event.FromString,
                _registered_method=True)
        self.EditSchedule = channel.unary_unary(
                '/questkeeper.events.commands_service.EventsCommands/EditSchedule',
                request_serializer=events_dot_commands__service__pb2.EditScheduleRequest.SerializeToString,
                response_deserializer=events_dot_models__pb2.Event.FromString,
                _registered_method=True)
        self.EditOrganization = channel.unary_unary(
                '/questkeeper.events.commands_service.EventsCommands/EditOrganization',
                request_serializer=events_dot_commands__service__pb2.EditOrganizationRequest.SerializeToString,
                response_deserializer=events_dot_models__pb2.Event.FromString,
                _registered_method=True)
        self.PublishEvent = channel.unary_unary(
                '/questkeeper.events.commands_service.EventsCommands/PublishEvent',
                request_serializer=events_dot_commands__service__pb2.PublishEventRequest.SerializeToString,
                response_deserializer=events_dot_models__pb2.Event.FromString,
                _registered_method=True)
        self.CancelEvent = channel.unary_unary(
                '/questkeeper.events.commands_service.EventsCommands/CancelEvent',
                request_serializer=events_dot_commands__service__pb2.CancelEventRequest.SerializeToString,
                response_deserializer=events_dot_models__pb2.Event.FromString,
                _registered_method=True)


class EventsCommandsServicer(object):
    """--- domain commands service (write) ---
    """

    def CreateEvent(self, request, context):
        """event lifecycle
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditBasics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditOrganization(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventsCommandsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEvent,
                    request_deserializer=events_dot_models__pb2.EventInfo.FromString,
                    response_serializer=events_dot_models__pb2.Event.SerializeToString,
            ),
            'EditBasics': grpc.unary_unary_rpc_method_handler(
                    servicer.EditBasics,
                    request_deserializer=events_dot_commands__service__pb2.EditBasicsRequest.FromString,
                    response_serializer=events_dot_models__pb2.Event.SerializeToString,
            ),
            'EditSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.EditSchedule,
                    request_deserializer=events_dot_commands__service__pb2.EditScheduleRequest.FromString,
                    response_serializer=events_dot_models__pb2.Event.SerializeToString,
            ),
            'EditOrganization': grpc.unary_unary_rpc_method_handler(
                    servicer.EditOrganization,
                    request_deserializer=events_dot_commands__service__pb2.EditOrganizationRequest.FromString,
                    response_serializer=events_dot_models__pb2.Event.SerializeToString,
            ),
            'PublishEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishEvent,
                    request_deserializer=events_dot_commands__service__pb2.PublishEventRequest.FromString,
                    response_serializer=events_dot_models__pb2.Event.SerializeToString,
            ),
            'CancelEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelEvent,
                    request_deserializer=events_dot_commands__service__pb2.CancelEventRequest.FromString,
                    response_serializer=events_dot_models__pb2.Event.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'questkeeper.events.commands_service.EventsCommands', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('questkeeper.events.commands_service.EventsCommands', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EventsCommands(object):
    """--- domain commands service (write) ---
    """

    @staticmethod
    def CreateEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.events.commands_service.EventsCommands/CreateEvent',
            events_dot_models__pb2.EventInfo.SerializeToString,
            events_dot_models__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EditBasics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.events.commands_service.EventsCommands/EditBasics',
            events_dot_commands__service__pb2.EditBasicsRequest.SerializeToString,
            events_dot_models__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EditSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.events.commands_service.EventsCommands/EditSchedule',
            events_dot_commands__service__pb2.EditScheduleRequest.SerializeToString,
            events_dot_models__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EditOrganization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.events.commands_service.EventsCommands/EditOrganization',
            events_dot_commands__service__pb2.EditOrganizationRequest.SerializeToString,
            events_dot_models__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.events.commands_service.EventsCommands/PublishEvent',
            events_dot_commands__service__pb2.PublishEventRequest.SerializeToString,
            events_dot_models__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.events.commands_service.EventsCommands/CancelEvent',
            events_dot_commands__service__pb2.CancelEventRequest.SerializeToString,
            events_dot_models__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
