# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: qk_api_contracts/grpc/events/commands_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'qk_api_contracts/grpc/events/commands_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from qk_api_contracts.grpc.events import models_pb2 as qk__api__contracts_dot_grpc_dot_events_dot_models__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3qk_api_contracts/grpc/events/commands_service.proto\x12\x12questkeeper.events\x1a\x1fgoogle/protobuf/timestamp.proto\x1a)qk_api_contracts/grpc/events/models.proto\"o\n\x11\x45\x64itBasicsRequest\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07summary\x18\x03 \x01(\t\x12\x0e\n\x06system\x18\x04 \x01(\t\x12\x18\n\x10\x65xpected_version\x18\x05 \x01(\x04\"\xa1\x01\n\x13\x45\x64itScheduleRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12.\n\ntime_start\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x08time_end\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x18\n\x10\x65xpected_version\x18\x05 \x01(\x04\"_\n\x17\x45\x64itOrganizationRequest\x12\x10\n\x08location\x18\x01 \x01(\t\x12\x18\n\x10\x61\x64\x64itional_links\x18\x02 \x03(\t\x12\x18\n\x10\x65xpected_version\x18\x03 \x01(\x04\"A\n\x13PublishEventRequest\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x18\n\x10\x65xpected_version\x18\x02 \x01(\x04\"@\n\x12\x43\x61ncelEventRequest\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x18\n\x10\x65xpected_version\x18\x02 \x01(\x04\x32\xb0\x04\n\x0e\x45ventsCommands\x12U\n\x0b\x43reateEvent\x12$.questkeeper.events.models.EventInfo\x1a .questkeeper.events.models.Event\x12U\n\nEditBasics\x12%.questkeeper.events.EditBasicsRequest\x1a .questkeeper.events.models.Event\x12Y\n\x0c\x45\x64itSchedule\x12\'.questkeeper.events.EditScheduleRequest\x1a .questkeeper.events.models.Event\x12\x61\n\x10\x45\x64itOrganization\x12+.questkeeper.events.EditOrganizationRequest\x1a .questkeeper.events.models.Event\x12Y\n\x0cPublishEvent\x12\'.questkeeper.events.PublishEventRequest\x1a .questkeeper.events.models.Event\x12W\n\x0b\x43\x61ncelEvent\x12&.questkeeper.events.CancelEventRequest\x1a .questkeeper.events.models.Eventb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'qk_api_contracts.grpc.events.commands_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EDITBASICSREQUEST']._serialized_start=151
  _globals['_EDITBASICSREQUEST']._serialized_end=262
  _globals['_EDITSCHEDULEREQUEST']._serialized_start=265
  _globals['_EDITSCHEDULEREQUEST']._serialized_end=426
  _globals['_EDITORGANIZATIONREQUEST']._serialized_start=428
  _globals['_EDITORGANIZATIONREQUEST']._serialized_end=523
  _globals['_PUBLISHEVENTREQUEST']._serialized_start=525
  _globals['_PUBLISHEVENTREQUEST']._serialized_end=590
  _globals['_CANCELEVENTREQUEST']._serialized_start=592
  _globals['_CANCELEVENTREQUEST']._serialized_end=656
  _globals['_EVENTSCOMMANDS']._serialized_start=659
  _globals['_EVENTSCOMMANDS']._serialized_end=1219
# @@protoc_insertion_point(module_scope)
