# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from qk_api_contracts.grpc.events import models_pb2 as qk__api__contracts_dot_grpc_dot_events_dot_models__pb2
from qk_api_contracts.grpc.events import query_service_pb2 as qk__api__contracts_dot_grpc_dot_events_dot_query__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in qk_api_contracts/grpc/events/query_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EventsQueryStub(object):
    """--- queries service (read models/projections)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetEvent = channel.unary_unary(
                '/questkeeper.events.EventsQuery/GetEvent',
                request_serializer=qk__api__contracts_dot_grpc_dot_events_dot_query__service__pb2.GetEventRequest.SerializeToString,
                response_deserializer=qk__api__contracts_dot_grpc_dot_events_dot_models__pb2.Event.FromString,
                _registered_method=True)
        self.GetEventView = channel.unary_unary(
                '/questkeeper.events.EventsQuery/GetEventView',
                request_serializer=qk__api__contracts_dot_grpc_dot_events_dot_query__service__pb2.GetEventRequest.SerializeToString,
                response_deserializer=qk__api__contracts_dot_grpc_dot_events_dot_models__pb2.EventView.FromString,
                _registered_method=True)
        self.GetEventSummary = channel.unary_unary(
                '/questkeeper.events.EventsQuery/GetEventSummary',
                request_serializer=qk__api__contracts_dot_grpc_dot_events_dot_query__service__pb2.GetEventRequest.SerializeToString,
                response_deserializer=qk__api__contracts_dot_grpc_dot_events_dot_models__pb2.EventSummary.FromString,
                _registered_method=True)
        self.ListEvents = channel.unary_unary(
                '/questkeeper.events.EventsQuery/ListEvents',
                request_serializer=qk__api__contracts_dot_grpc_dot_events_dot_query__service__pb2.ListEventsRequest.SerializeToString,
                response_deserializer=qk__api__contracts_dot_grpc_dot_events_dot_query__service__pb2.ListEventsResponse.FromString,
                _registered_method=True)


class EventsQueryServicer(object):
    """--- queries service (read models/projections)
    """

    def GetEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEventView(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEventSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventsQueryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEvent,
                    request_deserializer=qk__api__contracts_dot_grpc_dot_events_dot_query__service__pb2.GetEventRequest.FromString,
                    response_serializer=qk__api__contracts_dot_grpc_dot_events_dot_models__pb2.Event.SerializeToString,
            ),
            'GetEventView': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEventView,
                    request_deserializer=qk__api__contracts_dot_grpc_dot_events_dot_query__service__pb2.GetEventRequest.FromString,
                    response_serializer=qk__api__contracts_dot_grpc_dot_events_dot_models__pb2.EventView.SerializeToString,
            ),
            'GetEventSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEventSummary,
                    request_deserializer=qk__api__contracts_dot_grpc_dot_events_dot_query__service__pb2.GetEventRequest.FromString,
                    response_serializer=qk__api__contracts_dot_grpc_dot_events_dot_models__pb2.EventSummary.SerializeToString,
            ),
            'ListEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEvents,
                    request_deserializer=qk__api__contracts_dot_grpc_dot_events_dot_query__service__pb2.ListEventsRequest.FromString,
                    response_serializer=qk__api__contracts_dot_grpc_dot_events_dot_query__service__pb2.ListEventsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'questkeeper.events.EventsQuery', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('questkeeper.events.EventsQuery', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EventsQuery(object):
    """--- queries service (read models/projections)
    """

    @staticmethod
    def GetEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.events.EventsQuery/GetEvent',
            qk__api__contracts_dot_grpc_dot_events_dot_query__service__pb2.GetEventRequest.SerializeToString,
            qk__api__contracts_dot_grpc_dot_events_dot_models__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEventView(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.events.EventsQuery/GetEventView',
            qk__api__contracts_dot_grpc_dot_events_dot_query__service__pb2.GetEventRequest.SerializeToString,
            qk__api__contracts_dot_grpc_dot_events_dot_models__pb2.EventView.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEventSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.events.EventsQuery/GetEventSummary',
            qk__api__contracts_dot_grpc_dot_events_dot_query__service__pb2.GetEventRequest.SerializeToString,
            qk__api__contracts_dot_grpc_dot_events_dot_models__pb2.EventSummary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questkeeper.events.EventsQuery/ListEvents',
            qk__api__contracts_dot_grpc_dot_events_dot_query__service__pb2.ListEventsRequest.SerializeToString,
            qk__api__contracts_dot_grpc_dot_events_dot_query__service__pb2.ListEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
