# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: qk_api_contracts/grpc/events/query_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'qk_api_contracts/grpc/events/query_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from qk_api_contracts.grpc import common_pb2 as qk__api__contracts_dot_grpc_dot_common__pb2
from qk_api_contracts.grpc.events import models_pb2 as qk__api__contracts_dot_grpc_dot_events_dot_models__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0qk_api_contracts/grpc/events/query_service.proto\x12\x12questkeeper.events\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\"qk_api_contracts/grpc/common.proto\x1a)qk_api_contracts/grpc/events/models.proto\"#\n\x0fGetEventRequest\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\"\xc9\x01\n\x11ListEventsRequest\x12\x11\n\tserver_id\x18\x01 \x01(\t\x12\x0e\n\x06system\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12)\n\x05start\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\'\n\x03\x65nd\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12-\n\x04page\x18\x06 \x01(\x0b\x32\x1f.questkeeper.common.PageRequest\"t\n\x12ListEventsResponse\x12\x36\n\x05items\x18\x01 \x03(\x0b\x32\'.questkeeper.events.models.EventSummary\x12&\n\x04page\x18\x02 \x01(\x0b\x32\x18.questkeeper.common.Page2\xf9\x02\n\x0b\x45ventsQuery\x12Q\n\x08GetEvent\x12#.questkeeper.events.GetEventRequest\x1a .questkeeper.events.models.Event\x12Y\n\x0cGetEventView\x12#.questkeeper.events.GetEventRequest\x1a$.questkeeper.events.models.EventView\x12_\n\x0fGetEventSummary\x12#.questkeeper.events.GetEventRequest\x1a\'.questkeeper.events.models.EventSummary\x12[\n\nListEvents\x12%.questkeeper.events.ListEventsRequest\x1a&.questkeeper.events.ListEventsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'qk_api_contracts.grpc.events.query_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETEVENTREQUEST']._serialized_start=184
  _globals['_GETEVENTREQUEST']._serialized_end=219
  _globals['_LISTEVENTSREQUEST']._serialized_start=222
  _globals['_LISTEVENTSREQUEST']._serialized_end=423
  _globals['_LISTEVENTSRESPONSE']._serialized_start=425
  _globals['_LISTEVENTSRESPONSE']._serialized_end=541
  _globals['_EVENTSQUERY']._serialized_start=544
  _globals['_EVENTSQUERY']._serialized_end=921
# @@protoc_insertion_point(module_scope)
